### ISSUE TITLE
Should find_one() support order_by just like find()?

### ISSUE THREAD

**Issue by ghostwords** [pudo/dataset#112]
Docs say, "Works just like find() but returns one result, or None."

Would simplify things like getting the latest (autogenerated) ID:
```python
id = list(
    db['table'].find(_limit=1, order_by='-id')
)[0]['id']
```

**Comment by stefanw** [comment]
Opened a PR that should fix this. Please note that `db['table'].insert(...)` returns the autogenerated id.

**Comment by ghostwords** [comment]
Nice, thanks and thanks for the tip!

Should the return be specified in the docs ([maybe here](http://dataset.readthedocs.org/en/latest/api.html#dataset.Table.insert))?
