### ISSUE TITLE
Support for IN clauses in raw SQL queries

### ISSUE THREAD

**Issue by ghostwords** [pudo/dataset#116]
Trying to do an IN clause in a raw SQL query; this is what I got so far:
```python
if ids:
    in_clause = "AND id IN (%s)" % ','.join(
        [str(int(id)) for id in ids])

sql = """SELECT url, error, COUNT(*) count
    FROM result
    WHERE error IS NOT NULL %s
    GROUP BY url, error
    ORDER BY count DESC""" % (in_clause if ids else "")

with dataset.connect(app.config['DATABASE_URL']) as db:
    result = db.query(sql)
```
Do you see any issues with this workaround?

This is related to #115. Dataset wraps around SQLAlchemy, which has no real support for IN clauses in raw text queries, from what I understand. While it looks like IN clauses are supported via SQLAlchemy's expression language, having to deal with it seems far away from "[making] using SQL databases in Python a breeze".

**Comment by pudo** [comment]
I see where your problem is, but I just don't know how a solution better than ``sqlalchemy.core`` would look like. Your query is complex, not just because of the IN clause, but also because it performs aggregation. What do you think of this, which is just ``sqlalchemy``: 

```python
from sqlalchemy.sql.expression import select
from sqlalchemy.sql import func, and_

db = dataset.connect(app.config['DATABASE_URL'])
table = db['result'].table
q = select([tbl.url, tbl.error, func.count(tbl.id).alias('count')],
           and_(table.error != None, id.in_(ids),
           from_obj=table, group_by=[tbl.url, tbl.error],
           order_by=func.count(tbl.id).desc())
result = db.query(q)
```

**Comment by ghostwords** [comment]
Cool, thanks for the code translation! Building SQL by string manipulation is pretty gross.

The gaps in raw SQL parameter substitution support are still a problem. I think they should at least get called out along with suggested workarounds in the docs somewhere.
