### ISSUE TITLE
"TypeError: isoformat() takes no keyword arguments" exception is raised when freezing date column to CSV

### ISSUE THREAD

**Issue by ghing** [pudo/dataset#117]
Date values in my result set cause a problem when trying to freeze to CSV using ``dataset.freeze()``.  These values are handled by [value_to_string()](https://github.com/pudo/dataset/blob/master/dataset/freeze/format/fcsv.py#L10) and an exception is raised when ``value.isoformat(sep=sep)`` is called.

The exception is raised because, while ``datetime.isoformat()`` takes a ``sep`` argument, ``date.isoformat()`` does not.  The condition, ``if isinstance(value, (datetime, date))`` captures both.

**Comment by pudo** [comment]
Can I just say: that is one beautiful bug report, thanks very much :) In any case, I've pushed a potential fix, can you give a thumbs up that it fixes the issue?

**Comment by pudo** [comment]
Handling this differently now.
