### ISSUE TITLE
result object keeps closing

### ISSUE THREAD

**Issue by eads** [pudo/dataset#122]
When working on a large result set (60,000 rows, give or take), I'm getting result object is closed errors about midway through processing:

```
sqlalchemy.exc.ResourceClosedError: This result object is closed.
```

**Comment by eads** [comment]
Just kidding! Turns out fancy python iterators like groupby and sqlalchemy results don't mix because the cursor gets exhausted before the loop finishes. Solution is to convert to in-memory object and then use groupby on that object.

**Comment by pudo** [comment]
Oh, good to know. I'm really sorry for asking this, but curiosity: why would you do ``itertools.groupby`` when you're talking to a SQL database anyway?

**Comment by eads** [comment]
Ha, it's a good question. The answer: Trying to generate a fairly complex nested data structure to write to the file system as JSON.

I was about to follow a follow-up issue but it's really more of a question related to this issue: does file freezing support nested output?

**Comment by pudo** [comment]
Nope, only splitting up into separate files based on path templates (i.e. ``/site/{{country}}/{{city}}/{{street}}.json``)...

**Comment by eads** [comment]
Basically we're going for output that looks a bit like:

```
{
 "agency": "Covington",
 "agency_type": "Sheriff", 
 "state": "AL", 
 "crimes": {
    "violent": {
        "2011": {"count": 25, "cleared": 7, "cleared_pct": 0.28}, 
        "2012": {"count": 39, "cleared": 11, "cleared_pct": 0.282}},
        "2013": {"count": 49, "cleared": 14, "cleared_pct": 0.285}, 
    }
  }
}
```

**Comment by eads** [comment]
Also, thank you!! dataset is freaking awesome!! The path templating for freezing is sweet and generally freezing is super slick. 

It was an easy problem to solve once I realized what was happening under the hood. At first I thought the connection was timing out or something because it's a decently large set of results.
