### ISSUE TITLE
Duplicate column name ID error when trying to loop

### ISSUE THREAD

**Issue by filipeteles** [pudo/dataset#123]
I have a file with multiple dictionaries, one in each line. I'm writing a script to read each line and insert into a MySQL database, using Dataset. I'm getting the following error when I run the script:

sqlalchemy.exc.OperationalError: (OperationalError) (1060, "Duplicate column name 'id'") b'ALTER TABLE `gownData` ADD COLUMN id INTEGER' ()

My code is:

    import ast
    import dataset

    db = dataset.connect('mysql://admin:*************@localhost/dataset')

    def insertInDatabse(dataToBeInserted):

        table = db['gownData']
        table.insert(dict(dataToBeInserted))
        db.commit()

    def popAndMergeDicts(line):

        dictLine = ast.literal_eval(line)
        tempDict = dictLine['billing_address']
        del dictLine['billing_address']
        for i in tempDict:
            dictLine[i] = tempDict[i]
            insertInDatabse(dictLine)
        return dictLine

    def process_file(filename):
        lines = tuple(open(filename))
        for line in lines[0:]:
            popAndMergeDicts(line)

    process_file('allOrdersData')

Any ideas what is going wrong?

**Comment by pudo** [comment]
There's something rotten about the way threading and DDL mix up sometimes in ways that lead to these errors. That also means they only show up the first time a script is run, but I still think it's worth some more investigation. Re-opening.

**Comment by pudo** [comment]
Sorry, I've just had another read of your sample code. The dictionary you are inserting appears to contain an ``id`` column value, while dataset tries to generate ``id`` automatically. The best workaround would be to place the ``id`` value into another field like this:

```python
def insertInDatabse(dataToBeInserted):
    data = dict(dataToBeInserted)
    data['source_id'] = data.pop('id', None)
    table = db['gownData']
    table.insert()
    db.commit()
```

**Comment by eads** [comment]
nota bene: If you has postgis installed, this also happens for columns named `geoid`
