### ISSUE TITLE
Why doesn't insert support **kwargs format

### ISSUE THREAD

**Issue by vskr** [pudo/dataset#126]
find() and find_one() support **kwargs which lets clients use those methods without having to wrap **filters inside a dict.

Why can't insert support the same.

Currently, syntax for inserting is

insert(dict(col_name=col_value,..))

Why can't it be insert(col_name=col_value)...

Just curious about the rationale behind those decisions.

**Comment by pudo** [comment]
The reason that ``insert`` would take a dict is to make it consistent with ``update`` and ``upsert``. Both of these have a second positional argument to define unique keys. It also makes sense given that ``find`` and ``find_one`` will return a dict - so you can easily round-trip data. 

I would be a bit reluctant to support an alternative call syntax for no reason, it's the kind of thing that makes the API less clear. Do you see a good reason?
