### ISSUE TITLE
Increment and decrement operators

### ISSUE THREAD

**Issue by vskr** [pudo/dataset#127]
Is it possible to increment/decrement a column's value without getting the column.

e.g.
UPDATE TABLE 
SET my_col = my_col - 1
WHERE my_id=some_id

Is it possible to simulate above query using dataset API.

**Comment by pudo** [comment]
You have two options: a) you do it non-atomically, b) you use ``sqlalchemy.core`` to define a query.
a): 

```python
data = table.find_one(my_id=some_id)
table.update({'my_id': data['my_id'], 'my_col': data['my_col'] - 1}, ['my_id'])
```
b)
```python
q = table.table.update().where(table.table.c.my_id==some_id)
q = q.values(my_col=table.table.c.my_col - 1)
db.execute(q)
```
I haven't tested the latter, would perhaps need some changing.
