### ISSUE TITLE
Greater than or Less than operators

### ISSUE THREAD

**Issue by vskr** [pudo/dataset#128]
Does dataset's find/find_one API support greater than (>, >=) or less than (<, <=) operators on numeric columns?

**Comment by pudo** [comment]
I really like the idea, but I'm not sure what the best API looks like. Django uses a special arguments syntax (e.g. ``foo_gt=5``), while SQLAlchemy (underlying dataset) uses operator overloading like this: ``.filter(table.column>=5)``.

The most natural thing to do with dataset would be to use a syntax along the lines of Django, but that would mean wrapping around SQLAlchemy and making it's functionality less visible. I would prefer to find a way to more conveniently expose SQLA's actual abstractions and accept them within dataset. The most simple version could look like this: 

```python
eng = dataset.connect()
tbl = eng['table']
for row in tbl.find(tbl.table.columns.foo >= 5):
    pass
```

Now, how to simplify that?

**Comment by akx** [comment]
I think a touch of magic in the `.find()` API wouldn't go amiss here. That is, looking for supported Django-style operators in the kwargs and transforming them into SQLAlchemy-style expressions.

```python
tbl.find(foo__gte=5, bar="quux")
# gets transformed into
tbl.find((tbl.table.c.foo >= 5) & (tbl.table.c.bar == "quux"))
```

**Comment by pudo** [comment]
PR anyone?

**Comment by femtotrader** [comment]
Blaze provide an elegant syntax for this

    db_uri = 'mysql+mysqlconnector://root:root@localhost:3306/test'
    table_name = 'data'
    table_uri = db_uri + '::' + table_name

    import dataset

    db = dataset.connect(db_uri)

    table = db[table_name]
    table.insert(dict(name='John Doe', age=37))
    table.insert(dict(name='Jane Doe', age=34, gender='female'))
    table.insert(dict(name='Jack Doe', age=47))

    import blaze

    dat = blaze.Data(table_uri)

    dat[dat.age > 35]

    ## -- End pasted text --
    Out[8]:
       id      name  age gender
    0   1  John Doe   37   None
    1   3  Jack Doe   47   None

    In [9]: type(dat[dat.age > 35])
    Out[9]: blaze.expr.expressions.Selection

see https://github.com/pudo/dataset/issues/137
