### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by srjgit** [pudo/dataset#129]
Hi,

Is this really an issue or am I missing some configuration :

$ python test_persistence.py 
Traceback (most recent call last):
  File "test_persistence.py", line 15, in <module>
    from .sample_data import TEST_DATA, TEST_CITY_1
ValueError: Attempted relative import in non-package

**Comment by pudo** [comment]
I'm not sure, I usually run tests with: 

```bash
$ nosetests test/test_persistence.py
```

Adding the stubs for running them directly, though.
