### ISSUE TITLE
Read-only access to (sqlite) database

### ISSUE THREAD

**Issue by bilderbuchi** [pudo/dataset#136]
I recently started using dataset for a little project. One feature I missed: I was reading from a database, which I (inexperienced that I am) did not want to affect/change/destroy. 
sqlite3 offers read-only access, see [here](https://docs.python.org/3.4/library/sqlite3.html#sqlite3.connect):
> If uri is true, database is interpreted as a URI. This allows you to specify options. For example, to open a database in read-only mode you can use:

> `db = sqlite3.connect('file:path/to/database?mode=ro', uri=True)`

I did not find a corresponding feature in dataset, and trying to append the mode string to the db path when `connect`ing in dataset did not work (as could be expected, I guess).

Is this something you would find useful and consider adding?

**Comment by pudo** [comment]
So ``dataset`` uses ``sqlalchemy`` to abstract over all database types, and I'm very reluctant to implement any workaround that they don't have. I've googled this a bit and can't see any sign of whether sqlalchemy is aware of sqlite read-only mode. The best I've seen is that you can pass in ``connect_args``, like this: http://docs.sqlalchemy.org/en/latest/dialects/sqlite.html#compatibility-with-sqlite3-native-date-and-datetime-types - maybe that can be used to pass the read-only flag (https://www.sqlite.org/c3ref/open.html)?

**Comment by bilderbuchi** [comment]
So, I tried to do this (among other equally unsuccessful variations), but it does not work:
```
db = dataset.connect('sqlite:///' + db_file + '?mode=ro', engine_kwargs={'connect_args': {'uri': True}})
# TypeError: 'mode' is an invalid keyword argument for this function
```
Apparently, I'm [not the only one](http://stackoverflow.com/q/27910829/599884) with this problem, a workaround is to do 
```
creator = lambda: sqlite3.connect('file:' + db_file + '?mode=ro', uri=True)
db = dataset.connect('sqlite:///' , engine_kwargs={'creator': creator})
db.tables

# ['itemDataValues',
#  'fulltextItems',
#  'tags',
#  'baseFieldMappingsCombined',
#  ....
```
So, is this a bug in sqlalchemy? something you can/should fix on your side? no idea...

**Comment by bilderbuchi** [comment]
and it works:
```
table = db['itemDataValues']
table.create_column('foo', sqlalchemy.BIGINT)
# OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: 'ALTER TABLE "itemDataValues" ADD COLUMN foo BIGINT']
```

**Comment by pudo** [comment]
Ok, that's an awful workaround, I'll give you that. But I'd rather not like to start incorporating workarounds for sqlalchemy in this project -- perhaps worth filing a ticket on their tracker?

**Comment by bilderbuchi** [comment]
Yeah, let's see - I don't have a [bitbucket account](https://bitbucket.org/zzzeek/sqlalchemy/issues?status=new&status=open), and wouldn't even know how to properly formulate it (DB knowledge == machine_epsilon), and the workaround is good enough for me for now. Feel free to close this on your side, and thanks for the help!
