### ISSUE TITLE
Differences between dataset and blaze/odo

### ISSUE THREAD

**Issue by femtotrader** [pudo/dataset#137]
Hello,

I'm new to dataset project.
I would like to know if you ever heard of blaze/odo
http://blaze.pydata.org/
http://odo.readthedocs.org/en/latest/
I had myself never heard of until recently.

It will be nice if you could provide a comparison between these projects.

To my understanding:
- dataset can be great to dynamically create database
- blaze can be great to query database and provide Pandas like syntax (see https://github.com/pudo/dataset/issues/128 )

Kind regards

**Comment by pudo** [comment]
The data loading code in ``odo`` looks to be pretty amazing, seems they actually support generating the right ``COPY`` statements to load directly from a CSV file into a database. ``dataset`` is probably less oriented towards the handling of large datasets, and more targeted at handling smaller amounts of fairly disorganised data. In terms of the query language, it'd be cool to catch up with ``odo`` to some extend, definitely need some better query tools in ``dataset``!
