### ISSUE TITLE
Dataset should provide a kind of permission mechanism

### ISSUE THREAD

**Issue by femtotrader** [pudo/dataset#139]
Hello,

I notice how it's simple with dataset to put data in a table, add some rows...
but I wonder if there isn't a way to define (either at database level or at table level) some
permission.

For example, SELECT are allowed, INSERT are allowed but no ALTER ...

Kind regards

**Comment by pudo** [comment]
These are handled in the database, through user accounts. I'm incredibly reluctant to put complex logic like this - which people may come to depend on for actual security - into dataset. Dataset is a thin layer on top of SQLAlchemy.

If you need to precisely control who creates columns when and have enforcement of that, then dataset is not your tool.
