### ISSUE TITLE
datafreeze csv serializer with quoting

### ISSUE THREAD

**Issue by jjelosua** [pudo/dataset#141]
I think it would be a good option to allow the quotation of nonnumerical values on the csv formats of datafreeze, at least I have a good use case for cartodb importing.

another serializer would be an option not to disturb previous developments I propose "csv_nnquote".

I would be happy to issue a pull request if you see that functionality as a new serializer, maybe there's a better way to approach it.

**Comment by pudo** [comment]
Quoting string values sounds sensible to me, would be cool to have that in. Can't that be achieved with Python csv dialects, though? I also wonder how hard it would be to have some syntax for serializer arguments/flags, such as csv+quotetext+tab -- but in any case, a pull request will be much appreciated.

**Comment by pudo** [comment]
Closing, need to move tickets like this to ``datafreeze``.
