### ISSUE TITLE
Key on multiple columns

### ISSUE THREAD

**Issue by csu** [pudo/dataset#142]
Is it possible to key on multiple columns on one table?

**Comment by pudo** [comment]
I'm sorry, but can you clarify: do you mean creating an index on multiple columns, or updating on multiple columns? (in these cases: yes), or do you mean an actual composite primary key? (in that case: you'd need to hack a bit)

**Comment by csu** [comment]
A composite primary key (so no tuples can be added with values for the keyed columns that match those of another, already added tuple).

**Comment by pudo** [comment]
In that case you can [fall back to SQLAlchemy to create the desired index](http://docs.sqlalchemy.org/en/latest/core/constraints.html#unique-constraint). A pull request to the [create_index](https://github.com/pudo/dataset/blob/master/dataset/persistence/table.py#L269) function to add a ``unique`` flag would obviously also be appreciated :)

**Comment by csu** [comment]
Sounds good. Thanks for the prompt response!
