### ISSUE TITLE
Table.drop() does not remove the table from Database.tables

### ISSUE THREAD

**Issue by jbjorne** [pudo/dataset#146]
I think I found a bug in Table.drop(). When calling Table.drop() the table is dropped from the database, but the table name still remains in the Database.tables property. I think this is because in Table.drop() the table name is removed only from Database._tables but it remains in Database.metadata.

The issue can be seen with the following test program:
```python
import os, dataset

def showTables(db):
  return db.tables, db.metadata.tables.keys(), db._tables.keys()

dbName = "testDrop.db"
if os.path.exists(dbName):
  os.remove(dbName)
db = dataset.connect("sqlite:/// " + dbName)
print "Tables after connecting:", showTables(db)
db["mytable"]
print "Tables after calling 'db[\"mytable\"]':", showTables(db)
db["mytable"].drop()
print "Tables after calling 'db[\"mytable\"].drop()':", showTables(db)
```

The output from the program is:
```
Tables after connecting: ([], [], [])
Tables after calling 'db["mytable"]': (['mytable'], ['mytable'], ['mytable'])
Tables after calling 'db["mytable"].drop()': (['mytable'], ['mytable'], [])
```

In the test program the table "mytable" remains in db.metadata.tables even after the call to db["mytable"].drop().

I'm using dataset  0.6.1 with SQLite on Ubuntu.

**Comment by stefanw** [comment]
I created a test case in 47917c686756a390fc6eebd300ec394aafd9f021 that [will likely fail here](https://travis-ci.org/pudo/dataset/builds/102443227).

@pudo Any good reason for [this `|`ing these `set`s here](https://github.com/pudo/dataset/blob/47917c686756a390fc6eebd300ec394aafd9f021/dataset/persistence/database.py#L136)?

Should we refresh metadata or just use `._tables`?

**Comment by pudo** [comment]
This has been fixed for a while, not sure why the issue is still open.
