### ISSUE TITLE
dataset.freeze should not close provided fileobj

### ISSUE THREAD

**Issue by madprog** [pudo/dataset#147]
For some reason, I want to freeze some data to a memory file ; in my case, a `io.StringIO`. According to [its documentation](https://docs.python.org/3/library/io.html#io.StringIO):

> The text buffer is discarded when the close() method is called.

I could write a failing script:
```python
import dataset
import io
import traceback

database = dataset.connect('sqlite:///db.sqlite')
table = database['my_table']
table.delete()
table.insert_many([
    dict(name='Apples', count=2),
    dict(name='Bananas', count=3),
    dict(name='Carrots', count=4),
])  

for fmt in ('json', 'csv', 'tabson'):
    print('Trying with %s' % fmt)
    try:
        with io.StringIO() as my_file:
            dataset.freeze(table.all(), format=fmt, fileobj=my_file)

            print('%s output: %r' % (fmt, my_file.getvalue()))
    except:
        traceback.print_exc()
```

It fails for each of the formats:

> ```
Trying with json
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    print('%s output: %r' % (fmt, my_file.getvalue()))
ValueError: I/O operation on closed file
Trying with csv
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    print('%s output: %r' % (fmt, my_file.getvalue()))
ValueError: I/O operation on closed file
Trying with tabson
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    print('%s output: %r' % (fmt, my_file.getvalue()))
ValueError: I/O operation on closed file
```

Do you agree that when `fileobj` is provided, closing it should be the task of the caller?

**Comment by pudo** [comment]
Hadn't actually used this with fileobjs, very good point.
