### ISSUE TITLE
table.find() leaves query open, can't run operations inside loop

### ISSUE THREAD

**Issue by pudo** [pudo/dataset#15]
Apparently, table.find() blocks any access to the DB so that one cannot update() or do anything else inside a loop based on find().

**Comment by eads** [comment]
The same thing happens if you do something like:

```
results = db.query('select * from data')
for row in results:
   row['foo'] = 1
   table.update(row, ['id'])
```

@Dahlgren's solution wrapping the call in `list()` fixed it for me.

**Comment by eads** [comment]
Just tested this in a project using dataset. Works great!
