### ISSUE TITLE
dataset.freeze should not declare parameters for specific formatter

### ISSUE THREAD

**Issue by madprog** [pudo/dataset#150]
When you look at the `dataset.freeze` signature:

    dataset.freeze(result, format='csv', filename='freeze.csv', fileobj=None, prefix='.',
                   meta={}, indent=2, mode='list', wrap=True, callback=None, **kw)

`meta`, `indent`, `wrap` and `callback` don't mean anything for the csv formatter. They are specific to the json (and tabson, as it inherits json).
I have the idea to add new parameters for json , and I think that the list of arguments for this function is already quite long.
What about documenting them -- in readthedocs -- and removing them from the function declaration?
Nothing would break, as they still are caught by `kw`, and you don't have to add them by hand to `kw`.

This would allow managing the formatters as plugins: dataset.freeze doesn't need to know about their parameters, and in the future you could even pass a user class as `format`, to allow users creating their own formatters.

**Comment by pudo** [comment]
Looks good to me, you're right about them being inconsistent!

**Comment by madprog** [comment]
Here is the PR. I was waiting for your thoughts about this before polluting your issues :wink:

**Comment by pudo** [comment]
Thanks! Merged it and added some weird PEP8 formatting.
