### ISSUE TITLE
Question: what types of fields are supported?

### ISSUE THREAD

**Issue by gregorleban** [pudo/dataset#153]
Hi,
sorry for leaving this question as an issue, but I didn't find a more appropriate place to get an answer. I'm experimenting with dataset and would like to know if it's possible to insert items that have values that are not of basic types - such as dict, for example. 
Calling the bottom line, for example, throws an error: 

    table.insert({"name": 'John Doe', "age": 46, "country": 'China', "extra": { "a": 1, "b": "asdf" } })

and I'm not sure if it's just a settings thing or is it not supported.

Thank you for your help. The package looks very cool and useful!
Best,
Gregor

**Comment by stefanw** [comment]
`dataset` depends on sqlalchemy which stores data in *relational* databases. You can serialise your complex structures to strings (e.g. with JSON).

**Comment by pudo** [comment]
It'd be cool to add database-specific support for stuff like Postgres' ``JSONB``, though. Using it in other apps and it's really convenient.

**Comment by catmeme** [comment]
Darn, I was hoping for that ability as well. Serializing is an okay solution.
