### ISSUE TITLE
How to manage one-to-many/serialized data such as tags?

### ISSUE THREAD

**Issue by minthemiddle** [pudo/dataset#158]
How should I manage data that in a traditional database I would save in a one-to-many relationship? Let's say I have a `song` with the attributes `artist`, `length` and `title`. I can save all those easily with `dataset`. However, if I wanted to add a column with tags where more than one entry is possible, such as `party`, `rock`, `acoustic` and the like, I have no clue how to do that.

In the documentation I could not find any reference to `foreign_key` or `one-to-many` or anything like that. So I get this is not intended. Actually I am not referring to a difficult one-to-many relationship, rather for tagging or such.

Next idea was to save the tags as JSON and save it as text. `Sqlite3` has a pretty extension `json1`, and [Charles Leifer shows](http://charlesleifer.com/blog/using-the-sqlite-json1-and-fts5-extensions-with-python/) how to use it with `Peewee`. Saving JSON of course works, but I have no clue of how to search within those tags - for example: Show all `rock` songs.

Well, obviously `dataset` does not support JSON1 yet. So I wonder how you would manage such a tag-like system, especially searching within it.

**Comment by pudo** [comment]
Two points: I'd love to support relevant storage types for nested objects in ``dataset``, ie. the JSON types that already exist in MySQL and Postgres and the SQLite extension you mention. Searching these is indeed harder, but there must be some syntax even for SQLite (in Postgres, it's just an arrow operator). So if you wanted to hack up support for any of this, I'd love to see the pull request. 

It's very different for relationships: ``dataset`` is based on ``sqlalchemy``, which includes a really well-designed ORM. I believe this is the best way to design a schema that actually needs the types of relationships you mention. My recommendation would be to use it, and I'd really try to avoid having that feature in here.
