### ISSUE TITLE
Subselect columns

### ISSUE THREAD

**Issue by edublancas** [pudo/dataset#167]
Hi, I need to find the greatest value for a column, so I'm doing this:

```python
row = table.find_one(order_by='-column')
most_recent = row['column']
```

However, one of the columns in `row` is quite big (PostGIS column) and I don't need it. Is there a way to avoid loading the entire row? So basically doing:

```sql
SELECT column FROM table ORDER BY column DESC LIMIT 1
```

I know that one of the options would be to use `query` with the SQLAlchemy core API but I'm wondering if there's a way to do it using the `dataset` API.

Another option would be to pass the query as a string, but I'm getting the table name at runtime, and I want to avoid SQL injection risks.

Thanks.

**Comment by pudo** [comment]
Hm.... to be honest, for a very simple query like this, I wonder if you might not just write it out in SQL:

```python
import dataset
engine = dataset.connect('.....')
(column_max, ) = engine.execute("SELECT MAX(column) FROM table")
```

**Comment by pudo** [comment]
Argh, just saw your last paragraph. in that case, perhaps this:

```python
table_name = 'foo'
if table_name not in engine:
     raise ValueError()
```

**Comment by edublancas** [comment]
Thanks! I guess I'll need to hardcode the SQL query. I think the ability to only select certain columns would be a great addition to dataset.

**Comment by pudo** [comment]
You're right. If you have a suggestion for a nice API to implement this (something pythonic), I'd love to discuss :)
