### ISSUE TITLE
Insert many ignore

### ISSUE THREAD

**Issue by gearlles** [pudo/dataset#171]
Make it possible to insert multiple items at once with `IGNORE` keyword. Something like:

``` python
rows = [dict(name='Dolly')] * 10000
table.insert_many_ignore(rows)
```

**Comment by DasFranck** [comment]
Any updates?

**Comment by pudo** [comment]
There's now an API: ``table.insert_ignore(row, keys)``. It doesn't use ``IGNORE``, since that only exists in some RDBMS, instead does a ``COUNT`` followed by an optional ``INSERT``.
