### ISSUE TITLE
support of custom datetime string (sqlalchemy.dialects.sqlite.DATETIME)

### ISSUE THREAD

**Issue by maxpietsch** [pudo/dataset#174]
My sqlite database contains columns with DATETIME type that is not stored in the format sqlalchemy.dialects.sqlite.DATETIME expects. This causes queries of these rows to fail with:

    /home/mp14/.mainenv/local/lib/python2.7/site-packages/dataset/persistence/util.pyc in __next__(self)
         72                 raise StopIteration
         73         try:
    ---> 74             return convert_row(self.row_type, next(self._iter))
         75         except StopIteration:
         76             self._iter = None
    
    /home/mp14/.mainenv/local/lib/python2.7/site-packages/dataset/persistence/util.pyc in convert_row(row_type, row)
         31     if row is None:
         32         return None
    ---> 33     return row_type(row.items())
         34 
         35 
    
    /home/mp14/.mainenv/local/lib/python2.7/site-packages/sqlalchemy/engine/result.pyc in items(self)
        161         """Return a list of tuples, each tuple containing a key/value pair."""
        162         # TODO: no coverage here
    --> 163         return [(key, self[key]) for key in self.keys()]
        164 
        165     def keys(self):
    
    ValueError: Couldn't parse datetime string: u'03/22/15 12:00:00'

sqlalchemy allows defining a custom regular expression but I cannot find a way to access that when using dataset:

http://docs.sqlalchemy.org/en/rel_1_0/dialects/sqlite.html#sqlalchemy.dialects.sqlite.DATETIME

    import re
    from sqlalchemy.dialects.sqlite import DATETIME
    dt = DATETIME(storage_format="%(day)02d/%(month)02d/%(year)02d %(hour)02d:%(min)02d:%(second)02d",
        regexp=r"(\d+)/(\d+)/(\d+) (\d+):(\d+):(\d+)")

Am I missing something?

**Comment by pudo** [comment]
Wow, I've never come across this, it's seems like a bit of a SQLite hack. I think you can make it happen, though, if you pass in the initialised ``DATETIME`` via the ``types=`` argument to the data change functions: https://github.com/pudo/dataset/blob/master/dataset/persistence/table.py#L62

**Comment by pudo** [comment]
Ok, closing this: it's a data cleaning issue, not really a function that ``dataset`` should support.
