### ISSUE TITLE
ensure argument confusing; documentation or code needs changing

### ISSUE THREAD

**Issue by j-christ** [pudo/dataset#175]
I really like dataset, so thanks for creating it.  However, I've found a confusing thing which took me way longer to understand than it should have, and I suspect others may have the same problem with the interface.

For Table.insert, the documentation states:

  "If ensure is set, any of the keys of the row are not table columns, they will be created automatically."

The default value for ensure is None.  Most people would consider ensure *not* set if it has the value None.  However, the operative line is:

`ensure = self.database.ensure_schema if ensure is None else ensure`

Which means that if ensure is `None`, the default, that the database schema **will** be altered.  This is confusing.  In keeping with the principle of least surprise, the default should not to modify the schema unless:

1) the user has passed ensure=True to insert, etc
2) the user passed ensure_schema=True to the database init function (which should not default to true either

**Comment by pudo** [comment]
It's intended to allow for setting a default, per database connection. ``None`` in this context means: "I don't have a specific preference here, do what I told you to do when I created the dataset instance." If you can name a better way for allowing for this default, please let me know.

As for ``ensure_schema`` being ``True`` by default: that's kind of the point of ``dataset`` - it's creating the schema as you push in data, and it's targeted at non-critical data e.g. stuff coming from scrapes. If your sense is that that's dangerous, it's a good indication that you're using dataset for a use case for which it isn't intended, and that you might want to switch to a proper ORM layer instead.
