### ISSUE TITLE
Getting "rowid" column when working with sqlite3

### ISSUE THREAD

**Issue by CRImier** [pudo/dataset#183]
Hi! Great library, designing a small educational course about databases in Python now - your library is one of those I will show =)

sqlite has a "rowid" column by default for all tables (except for "without rowid" tables, which I imagine aren't the majority), it's just that - the row number, which is useful sometimes. However, it seems to be not accounted for in the API. Any way to make it show among "table.columns", generally, avoiding writing my own queries (the reason why I'm using this library in the first place)? If that's a bug, I'd be glad to help but would love if you hinted which part of the code to look at =)

Cheers!

**Comment by pudo** [comment]
I've thought about this a little bit, and think that the downsides of this outweigh the benefits: if we show it in ``table.columns``, it should behave like a column, be droppable, insertable etc. -- all of which is not meant to be true. As for the benefit of accessing this implementation-specific field, I'm not clear what problem it solves that cannot also be addressed by the auto-generated ``id`` field?

Please understand my intentions: ``dataset`` is supposed to be a fairly simple, self-contained, database-agnostic system for data wrangling. If you want to do more clever stuff, I really recommend using ``sqlalchemy.core`` directly: it's very good in supporting DB-specific bits and still provides a good set of abstractions.
