### ISSUE TITLE
Primary and foreign key examples

### ISSUE THREAD

**Issue by sijis** [pudo/dataset#184]
Hi,

Are there any examples using primary and foreign keys? 

Assuming I have two tables like below

```
Table1: animal
pk  | value
----+------
1   | Dog
2   | Cat
3   | Penguin
...
```

```
Table 2: owner
pk  | owner | animal (fk)
----+-------+------------
100 | Sam   | 1
101 | Jules | 3
...
```

From what I can tell, I'd have to go the SQLalchemy route.

Am I missing some example in the docs?

Thanks.

**Comment by pudo** [comment]
You're right, unfortunately: dataset doesn't have explicit support for foreign keys. You can of course access them if they're there and use PKs explicitly, but I worry that further attempts to Pythonify table relationships will leave you with something that's just automatically an ORM. If you have an idea for a more lightweight, Pythonic interface, it'd be fun to discuss further
