### ISSUE TITLE
table.find can only show 5000 items

### ISSUE THREAD

**Issue by rosstang** [pudo/dataset#185]
table.find has a hidden parameter of _step which is default to 5000. It is undocumented and unexpected.

**Comment by stefanw** [comment]
`_step` is a private API that concerns influences how many rows at a time are fetched from the database. The `find` operation still returns all requested rows, but depending on the `_step` parameter it possibly uses more than one database query.

The `_step` parameter with a value of 5000 was introduced a long time ago in 6bbe8a0486db125c5b40bdaa23de6dcbe9eb2b2f. Internal pagination is used to not load too many rows into memory at once (assuming streaming does not work?). This default could be revisited.

However, `dataset` is a very high level way to access a database. ORMs usually hide how many raw SQL queries are executed in the background. `dataset` is even higher-level than usual ORMs, so users should really make no assumptions of how `dataset` interacts with the database.

@rosstang is there a specific behaviour of `_step` that bit you?

**Comment by rosstang** [comment]
The problem that I see is the following:

`
import pandas as pd
import dataset

db = dataset.connect('sqlite:///:memory:')
table = db['table']

for i in range(50):
    table.insert(dict(uid = i, text = "f1,f2,f3\n1,2,3\n4,5,6\n"))

conn = db.engine.raw_connection()

for i, r in enumerate(table.find(_step = 10)):
    print "i = %d, uid = %d" % (i, r["uid"])
    content = r["text"]
    csv = pd.read_csv(StringIO(content))
    csv.to_sql("result", conn, if_exists='append')
`

So, I am inserting 50 entries into table. Each of the entry has a field called text which is a csv. Then I tried to parse the csv one by one using pandas, and insert it into the database using to_sql method. It will end at the 10th step (I set _step to 10 to illustrate the problem).

Is it not supposed to use the raw_connection this way? Or is there any easy method to import pandas's dataframe into dataset?

Thanks!

**Comment by stefanw** [comment]
Peculiar behaviour. I don't know exactly what `pandas` does with the connection, but apparently it somehow resets the underlying result proxy so it's empty after one iteration.

One way to "solve" this, is to use `list(enumerate(table.find(_step = 10)))` which will force evaluation and execute all necessary queries beforehand.

@pudo have you seen this before? Should we expose the underlying raw connection?

**Comment by pudo** [comment]
@rosstang can you try using version 0.8 of dataset and ``db.executable`` instead of the raw connection? This will make pandas use the same DB connection as dataset, which may make more sense with SQLite memory databases.

**Comment by pudo** [comment]
Closing, unless ``db.executable`` can be shown not to work.
