### ISSUE TITLE
Mysql Select privilege connect error

### ISSUE THREAD

**Issue by clarkchen** [pudo/dataset#187]
I run connect method in ubuntu server with an account has only **select** privilege, bug got an exception, 

```
OperationalError: (_mysql_exceptions.OperationalError) (1142, "SHOW VIEW command denied to user 'xxxx'@'xxxx' for table 'xxxx'") [SQL: u'SHOW CREATE TABLE `xxxx`']
```
should i grant SHOW VIEW privilege to the account, 

or is there some magic settings to be done to avoid such exception

**Comment by clarkchen** [comment]
hello...?

**Comment by clarkchen** [comment]
@pudo ,,,

**Comment by pudo** [comment]
``dataset`` will always use some reflection, I think, so you might have to grant more than select. You can try and avoid/delay it by passing these arguments into the constructor:

```python
import dataset
db = dataset.connect('...uri...', reflect_metadata=False, reflect_views=False)
```

**Comment by clarkchen** [comment]
...cool...
