### ISSUE TITLE
unicode encoding 

### ISSUE THREAD

**Issue by nico1996it** [pudo/dataset#191]
In the api documentation i can read 

> url can be any valid SQLAlchemy engine URL.

but if do 
```
import dataset
from sqlalchemy import create_engine

engine = create_engine('mysql://USER:PASS!@SERVER/DATABASE' , encoding='latin1',)

db = dataset.connect(url=engine)
```
i get 
`AttributeError: 'Engine' object has no attribute 'find'`

if i do 
`db = dataset.connect('mysql://USER:PASS!@SERVER/DATABASE' , encoding='latin1',)`

i get 
`TypeError: connect() got an unexpected keyword argument 'encoding'`

**Comment by kantandane** [comment]
I'm looking for an answer, I have the same problem.. need to specify a charset to my requests and I don't find a way to do so with dataset lib !

**Comment by stefanw** [comment]
@kantandane Your approach to use `engine_kwargs` is correct. `dataset.connect` just calls `sqlalchemy`'s `create_engine` internally with `url` and `**engine_kwargs`.

Unless you can confirm that it works using sqlalchemy directly with `create_engine` and not with `dataset`, this doesn't seem to be a `dataset` bug. Feel free to reopen.
