### ISSUE TITLE
Feature request:  _step kwarg for database.query() just like table.find()

### ISSUE THREAD

**Issue by ceturc** [pudo/dataset#192]
Feature request: Any interest in bringing the _step kwarg to database.query()?

I'm glad to submit a P/R if there's interest in considering it.

I've patched my local copy to add a _step= kwarg to database.query(), similar to table.find(), it works really well.

When I switched to using database.query() from table.find() for one special case, I really missed the _step feature from table.find().  My database table is really large, so the _step is necessary to avoid all results coming down into memory.

Thanks again for an amazing project!

**Comment by pudo** [comment]
Please do submit that PR!
