### ISSUE TITLE
Dependancies?

### ISSUE THREAD

**Issue by ds9133** [pudo/dataset#194]
Hi,

I'm having some troubles importing the library. Installing ok, but during import:

```
row = {normalize_column_name(k): v for k, v in row.items()}
```

I'm using python 2.6.6, and my first guess is that this is not supported, although i can't actually find any dependancies on the documentation.

**Comment by stefanw** [comment]
The code you mentioned uses [dict comprehensions](https://www.python.org/dev/peps/pep-0274/) which are not available in Python 2.6. Python 2.6 end of life was in October 2013 and therefore it is not supported by `dataset`.
