### ISSUE TITLE
Database freeze not executing and not returning an exception either.

### ISSUE THREAD

**Issue by Olamyy** [pudo/dataset#198]
I have a database I'm attempting to export using dataset.
The export completes when i use a **freezefile.yaml** i.e when i do :

`datafreeze freezefile.yaml`

However when i try it from a script query, the export does not execute and does not return an error either.
What I'm trying is this.

  ```python
    query = self.db[table].all()
    try:
       dataset.freeze(query, format='csv', filename='data/data.csv')
    except Exception as error:
                print(error)

**Comment by pudo** [comment]
Can you try putting in the table directly, without the call to ``.all()``?

**Comment by Olamyy** [comment]
Still no difference.

**Comment by Olamyy** [comment]
Fixed.
Sorry, it was an error on my end.
Was writing to a different directory.
