### ISSUE TITLE
Deprecation warning FromClause.count()

### ISSUE THREAD

**Issue by fmder** [pudo/dataset#199]
It seems that since SQLAlchemy 1.1, FromClause.count() is deprecated and one should use func.count() instead. This is the full deprecation warning message.

```
python3.5/site-packages/dataset/persistence/table.py:440: SADeprecationWarning: ``FromClause.count()`` is deprecated. Counting rows requires that the correct column expression and accommodations for joins, DISTINCT, etc. must be made, otherwise results may not be what's expected. Please use an appropriate ``func.count()`` expression directly.
```

Here is the SQLAlchemy API link : http://docs.sqlalchemy.org/en/latest/core/selectable.html#sqlalchemy.sql.expression.Alias.count

**Comment by pudo** [comment]
Fixed in 0.8.
