### ISSUE TITLE
sqlite3 OperationalError

### ISSUE THREAD

**Issue by nmaas87** [pudo/dataset#200]
Hello there,

I always get following error

Traceback (most recent call last):
  File "./compile_results.py", line 58, in <module>
    for i in table_send:
  File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/util.py", line 73, in __next__
    return self.__next__()
  File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/util.py", line 67, in __next__
    if not self._next_chunk():
  File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/util.py", line 58, in _next_chunk
    chunk = self.result_proxy.fetchmany(self.step)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 997, in fetchmany
    self.cursor, self.context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 990, in fetchmany
    l = self.process_rows(self._fetchmany_impl(size))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 907, in _fetchmany_impl
    return self.cursor.fetchmany(size)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) SQL logic error or missing database

if I try to access dataset number 5000 of my sqlite database.

I am importing two databases into memory with about 60000 rows, which works.
I can also access the row 5000 (here id 10000) without error. However, as soon as the sqlite database reaches the for loop at this position, the whole python program crashes with the error shown above. So it seems like the database is working and got the imported data correctly (otherwise I could not access it before the for loop) - but something weird happens then. Any ideas?

Thank you very much for your help and great product :)

````
# import json from sender into memory database
db_send = dataset.connect('sqlite:///:memory:')
table_send = db_send['record']
with open(sendfile) as send:
    s = json.load(send)
table_send.insert_many(s["results"])
send.close()

# import json from receiver into memory database
db_recv = dataset.connect('sqlite:///:memory:')
table_recv = db_recv['record']
with open(recvfile) as recv:
    r = json.load(recv)
table_recv.insert_many(r["results"])
recv.close()

# init variables for matching counter
count_search=0
count_found=0

#print len(table_send)
#test = table_send.find_one(id=9998)
#print test['id']
#test = table_send.find_one(id=10000)
#print test['id']
#test = table_send.find_one(id=10002)
#print test['id']

# iterate through sender results, set file as sent
# match checksum of sent files to received files
# if matches, include time details of receiver and set received
# update results
for i in table_send:
        print i['id']
        i['file_sent'] = 1
        count_search += 1
        res_recv = table_recv.find_one(filechecksum=i['filechecksum'])
        i['file_sent'] = 1
        if res_recv != None:
                count_found += 1
                #print i['filechecksum'] + ':' + res_recv['filechecksum']
                i['r_time_start'] = res_recv['time_start']
                i['r_time_end'] = res_recv['time_end']
                i['r_time'] = res_recv['time']
                i['file_received'] = 1
        table_send.update(i,['id'])
````

**Comment by nmaas87** [comment]
From reading, it could be a problem with _step 5000 like mentioned here https://github.com/pudo/dataset/issues/185. How can I get around this problem?

**Comment by stefanw** [comment]
This might be caused by looping over a table while changing it (`table_send.update`). I speculate that this possibly resets some internal cursor which puts the loop in an inconsistent state. Also the loop looks like it could be replaced by something simpler like a SQL statement.

It would be helpful, if you could boil this down to a test case.

**Comment by nmaas87** [comment]
@stefanw This works fine as long as I do not go over 5000 items. Smaller sets work without any problem :/

**Comment by stefanw** [comment]
OK, then you're right, it's related to #185 (which also has some cursor problems). Simple test case needed.

**Comment by nmaas87** [comment]
@stefanw Any idea how to get around that error? How can I change that _step to something bigger (i.e. something big enough so that it will span all my columns)

**Comment by pudo** [comment]
What version of dataset are you using? I wrote a new one, 0.8, yesterday and would like to know if that is a regression. If you are not using 0.8, try upgrading -- there's a very good chance it fixes your problem.

**Comment by nmaas87** [comment]
@pudo It is aregression, sadly.

I just tried it with dataset (0.8.0), I was working with 0.6.2 and 0.7.1 earlier and I had the same error:

`````
9992
search: 4996
9994
search: 4997
9996
search: 4998
9998
search: 4999
Traceback (most recent call last):
  File "./compile_results.py", line 58, in <module>
    for i in table_send:
  File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/util.py", line 70, in __next__
    return convert_row(self.row_type, next(self._iter))
  File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/util.py", line 53, in iter_result_proxy
    chunk = rp.fetchmany(step)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 1155, in fetchmany
    self.cursor, self.context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 1148, in fetchmany
    l = self.process_rows(self._fetchmany_impl(size))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 1065, in _fetchmany_impl
    return self.cursor.fetchmany(size)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) SQL logic error or missing database

````

**Comment by pudo** [comment]
Am I correct in saying that you're assigning two different names (``table_send``, ``table_recv``) to the same table (``record``) and then creating new columns within the loop? This may mess with SQLAlchemy's internal metadata in ways that cause it to emit illegal SQL. Can you try assigning the table only to one wrapper object?

**Comment by nmaas87** [comment]
@pudo 

Sorry, these are two different tables.
As you can see, both dbs (db_send / db_recv) are created as two different sqlite databases in memory.
These are created from two different json files (sendfile and recvfile).
After that, I iterate through all entrys in the record table of the db_send [shortcut table_send], look for entries with the same checksum in the record table of db_recv [shortcut table_recv] and then modify settings in the db_send table / table_send with values from this found table.

So they are seperate from each other and should not be able to cause any trouble - and it works very well, as long as I stay under the 5000 entries limit, as said :/

**Comment by nmaas87** [comment]
@pudo / @stefanw Anything new :)? Is there anything that I could test to get this problem fixed? Thanks a lot for your time!

**Comment by nmaas87** [comment]
I created a small program to show the problem:

````
#!/usr/bin/python
#
# Import and activate in-Memory Database
import dataset, random
db_new = dataset.connect('sqlite:///:memory:')
table_new = db_new['record']
#
# generate send_db
db_send = dataset.connect('sqlite:///:memory:')
table_send = db_send['record']
for i in range(0,7500):
    table_send.insert(dict(id=i, value=random.random()))
    table_new.insert(dict(id=i, value=random.random()))
#
# generate recv_db
db_recv = dataset.connect('sqlite:///:memory:')
table_recv = db_recv['record']
for i in range(0,7500):
    table_recv.insert(dict(id=i, value=random.random()))
#
# iterate send_db and update it with values from recv_db
for i in table_send:
    print i['id']
    res_recv = table_recv.find_one(id=i['id'])
    res_new = table_new.find_one(id=i['id'])
    if res_recv != None:
        i['value2'] = res_recv['value']
        #res_new['value2'] = res_recv['value']
    table_send.update(i, ['id'])
    #table_new.update(res_new, ['id'])
````

will end in:
````
4995
4996
4997
4998
4999
Traceback (most recent call last):
  File "test_dataset_error.py", line 22, in <module>
    for i in table_send:
  File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/util.py", line 70, in __next__
    return convert_row(self.row_type, next(self._iter))
  File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/util.py", line 53, in iter_result_proxy
    chunk = rp.fetchmany(step)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 1155, in fetchmany
    self.cursor, self.context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 1148, in fetchmany
    l = self.process_rows(self._fetchmany_impl(size))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 1065, in _fetchmany_impl
    return self.cursor.fetchmany(size)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) SQL logic error or missing database
````

while 


````
#!/usr/bin/python
#
# Import and activate in-Memory Database
import dataset, random
db_new = dataset.connect('sqlite:///:memory:')
table_new = db_new['record']
#
# generate send_db
db_send = dataset.connect('sqlite:///:memory:')
table_send = db_send['record']
for i in range(0,7500):
    table_send.insert(dict(id=i, value=random.random()))
    table_new.insert(dict(id=i, value=random.random()))
#
# generate recv_db
db_recv = dataset.connect('sqlite:///:memory:')
table_recv = db_recv['record']
for i in range(0,7500):
    table_recv.insert(dict(id=i, value=random.random()))
#
# iterate send_db and update it with values from recv_db
for i in table_send:
    print i['id']
    res_recv = table_recv.find_one(id=i['id'])
    res_new = table_new.find_one(id=i['id'])
    if res_recv != None:
        #i['value2'] = res_recv['value']
        res_new['value2'] = res_recv['value']
    #table_send.update(i, ['id'])
    table_new.update(res_new, ['id'])
````
will work all the way through the 7500 values.
````
7491
7492
7493
7494
7495
7496
7497
7498
7499
````
The problem seems to be that you're only allowed to changes values in a table that is beeing itterated by, if thie table has less than 5000 entries. Other than  that, the error will occur. If you use a second db (which needs to be an independant copy of the first one) to iterate or modify - the program will work, as shown by the second example.

**Comment by pudo** [comment]
Ran the sample app against master, works now :)
