### ISSUE TITLE
deprecation warning from psycopg2 or sqlalchemy

### ISSUE THREAD

**Issue by yurzo** [pudo/dataset#201]
`dataset/persistence/table.py:400: SADeprecationWarning: ``FromClause.count()`` is deprecated. Counting rows requires that the correct column expression and accommodations for joins, DISTINCT, etc. must be made, otherwise results may not be what's expected. Please use an appropriate ``func.count()`` expression directly.`

In [4]: psycopg2.__version__
Out[4]: '2.6.1 (dt dec pq3 ext lo64)'

In [6]: sqlalchemy.__version__
Out[6]: '1.1.5'

**Comment by pudo** [comment]
Fixed in master.
