### ISSUE TITLE
about table.delete

### ISSUE THREAD

**Issue by wlccgp3** [pudo/dataset#202]
why it's delete all when I use table.delete({'a': 1))?
could you hlep me?

**Comment by pudo** [comment]
Could you try with ``table.delete(a=1)`` or ``table.delete(**{'a': 1})``? Passing in a dict will not construct a proper filter.

**Comment by wlccgp3** [comment]
thanks a lot for your reply

**Comment by lukestanley** [comment]
I think Dataset is great but this makes it far too easy to loose data. 
If there are arguments, surely it shouldn't just do self.table.delete()
I can do a trivial pull request to fix this later if desired.

**Comment by lukestanley** [comment]
Also the documentation says "If no arguments are given, all records are deleted." but currently this happens when arguments ARE given. It would be more correct if it said "If no keyword arguments are given, all records are deleted."

**Comment by stefanw** [comment]
3f330df20fa6e0bd4390ed133ef65eeba0fb17f3 will now check for arguments in delete and raise an error when arguments are given that are not `sqlalchemy` clauses. It was indeed a bug.

**Comment by lukestanley** [comment]
Fast work @stefanw.
Anyone have any idea when this fix will arrive at  https://pypi.python.org/pypi/dataset ?
