### ISSUE TITLE
Column creation in context transaction fails in Python 3.6 sqlite

### ISSUE THREAD

**Issue by fmder** [pudo/dataset#203]
Using Python3.6, the following code raises an operational error saying that the column does not exist

````python
from dataset import connect
db = connect("sqlite:///test.db")
with db as tx:
    tx["result"].insert({"foo": "bar"})
````

even using `ensure=True` raises the error.

I forked dataset and setup a travis-ci to reproduce the error : https://travis-ci.org/NovaSyst/dataset

**Comment by DomDellaSera** [comment]
Try this:
`
from dataset import connect
db = connect()
db['result'].insert({'foo': 'bar'})
print(db['result'].columns)
`

**Comment by fmder** [comment]
Yes I know, the non context works as usual. The problem is with the context
manager.

Le 28 févr. 2017 6:30 AM, "Dominic Della Sera" <notifications@github.com> a
écrit :

**Comment by fmder** [comment]
I think this has to do with [this note](https://dataset.readthedocs.io/en/latest/api.html#dataset.Database.begin) in the documentation of the `database.begin()` method:

> NOTICE: Schema modification operations, such as the creation of tables or columns will not be part of the transactional context.

**Comment by pudo** [comment]
Fixed in master. Thanks for reporting!
