### ISSUE TITLE
Incorrect String Value

### ISSUE THREAD

**Issue by Dennis-Duarte-Mariana** [pudo/dataset#205]
Hi, i am trying this simple code

db = dataset.connect('mysql://root:@localhost/aula5bdis')

table = db['curso']

john = table.find_one(nome="JDennis")

, but it keeps throwing this error.

C:\Python27\lib\site-packages\sqlalchemy\engine\default.py:450: Warning: (1366L, "Incorrect string value: '\\xE3o de ...' for column 'VARIABLE_VALUE' at row 478")
  cursor.execute(statement, parameters)

**Comment by pudo** [comment]
It sounds to me like you're trying to push some suspicious bytestrings into a column. All dataset text fields are supposed to be Unicode by default. If you want to insert or query data you should do that either using plain ASCII bytestrings, or you need to decode the data to unicode. Let me know if this helps.
