### ISSUE TITLE
sqlalchemy.BigInteger (bigserial) is not supported as primary key type

### ISSUE THREAD

**Issue by daniel-surename** [pudo/dataset#206]
It is impossible to insert a row who's id column is a big integer:

`table = db['temptable']`
`insertee = {'id': 222641234407424, 'foo':'bar'}`
`table.insert(insertee, ensure=True, types={'id': sqlalchemy.BigInteger})`

**Comment by adelleodel** [comment]
in my condition, i can't even create the table. it keep 'hang' in for the program.

**Comment by pudo** [comment]
In master, this is fixed. You can make a bigint PK table like this:

```
foo = db.get_table('foo', primary_type=db.types.bigint)
```
