### ISSUE TITLE
Unexpected behavior when dropping and re-creating table 

### ISSUE THREAD

**Issue by jasonhildebrand** [pudo/dataset#208]
I'm liking dataset - thanks for your work on it!

I saw in the documentation for drop_table:   If you want to re-create the table, make sure to get a fresh instance from the Database.

I thought I could get a fresh instance by invoking create_table explicitly, as follows:

    db['test'].drop()
    table = db.create_table('test', primary_id='name')
    assert table.columns == ['name'], table.columns
    # Fails with: AssertionError: ['id', 'name']

But found that my table then contains an unwanted 'id' column.  I believe this is added implicitly when I do db['test'].drop(), and is somehow being cached.

After some digging I found that adding a db.update_table() call solves this issue:

    db['test'].drop()
    db.update_table('test')
    table = db.create_table('test', primary_id='name')
    assert table.columns == ['name'], table.columns

If possible it would be good to to fix this unexpected behavior, so that the call to update_table() is not necessary.  But in the meantime, it would help new users if you could mention update_table() in the docs for drop_table.

**Comment by jasonhildebrand** [comment]
This is using mysql - not sure if that makes any difference.

**Comment by pudo** [comment]
This is fully revamped in master, and the method ``update_table`` is gone. You will now be able to do something like this:

```
table = db.create_table('test', primary_id='name', primary_type=db.types.string)
table.insert({'name': 'Fluffy'})
table.drop()
table.insert({'name': 'Scruffy'})
assert len(table) == 1
```

i.e. drop and create handling are entirely transparent.

**Comment by jasonhildebrand** [comment]
Great improvement.  Thanks for your work on this!
