### ISSUE TITLE
Exception when using insert/upsert in transactions if new columns are added after first insert/upsert

### ISSUE THREAD

**Issue by jason1365** [pudo/dataset#209]
dataset seems to handle adding new columns well; however, within a transaction, it fails if there is a valid insert/upsert prior to a row of data that would require adding a new column. The columns list also seems to get the new column added in it's list; however, it doesn't make it into sqlite.

Code [dataset_issue.txt](https://github.com/pudo/dataset/files/1003084/dataset_issue.txt):
`db = dataset.connect('sqlite:///tmp/sandbox.db')
tablename = 'new_non-existant_Table'
db[tablename]
dict1 = {'id': '3270156573', 'price': 116000, 'shortPrice': '$116k'}
dict2 = {'id': '3269807036', 'price': 429000, 'shortPrice': '$429k', 'hasOpenHouse': True} 
with db as dbTransaction:
    print(dbTransaction[tablename].columns)
    data = dbTransaction[tablename].upsert(dict1, ['id'])
    print("new columns are added on the first insert/upsert")
    print(dbTransaction[tablename].columns)
    try:
        data = dbTransaction[tablename].upsert(dict2, ['id'])
    except Exception as e:
        print(str(e))
        print(dbTransaction[tablename].columns)
        print("Seems to now have the column...")
        try:
            data = dbTransaction[tablename].upsert(dict2, ['id'])
        except Exception as e2:
            print(str(e2))
            print("But the column actually isn't available...")
print("Final set of columns:")
print(db[tablename].columns)`

Results from code:
`['id']
new columns are added on the first insert/upsert
['id', 'price', 'shortPrice']
(sqlite3.OperationalError) table new_non-existant_Table has no column named hasOpenHouse [SQL: 'INSERT INTO "new_non-existant_Table" (id, price, "shortPrice", "hasOpenHouse") VALUES (?, ?, ?, ?)'] [parameters: ('3269807036', 429000, '$429k', 1)]
['id', 'price', 'shortPrice', 'hasOpenHouse']
Seems to now have the column...
(sqlite3.OperationalError) no such column: new_non-existant_Table.hasOpenHouse [SQL: 'SELECT "new_non-existant_Table".id, "new_non-existant_Table".price, "new_non-existant_Table"."shortPrice", "new_non-existant_Table"."hasOpenHouse" \nFROM "new_non-existant_Table" \nWHERE "new_non-existant_Table".id = ?\n LIMIT ? OFFSET ?'] [parameters: ('3269807036', 1, 0)]
But the column actually isn't available...
Final set of columns:
['id', 'price', 'shortPrice', 'hasOpenHouse']`

**Comment by jason1365** [comment]
I'm attaching an example of my workaround.
[dataset_issue2.txt](https://github.com/pudo/dataset/files/1003107/dataset_issue2.txt)

check to see if I have any new columns, `if(len(dict2.keys() - db[tablename].columns) > 0):`; close the transaction first, do the upsert, then re-open a transaction (for increased performance in a loop)

**Comment by pudo** [comment]
I've just confirmed this issue is addressed in ``master``, so it will be fixed with the next version of dataset, presumably in a few days. 

For what it's worth, you can how also use global tables with a transaction, like: 
```
import dataset
db = dataset.connect('sqlite:///sandbox.db')
table = db['new_non-existant_Table']
dict1 = {'price': 116000, 'shortPrice': '$116k'}
dict2 = {'price': 429000, 'shortPrice': '$429k', 'hasOpenHouse': True}
with db as tx:
    data = table.upsert(dict1, ['id'])
```
