### ISSUE TITLE
Question: Multiple values and/or wildcard lookup? 

### ISSUE THREAD

**Issue by Jwink3101** [pudo/dataset#213]
I am lazy and *really* looking forward to using `dataset` in my next (personal) project. 

While I can think of workarounds, I would really like to be able to insert multiple values for a key. For example:

    table.insert(dict(key=['val1','val2'])) # Causes SQL error on insert

And then be able to (quickly) query on `val1`. Alternatively, I could do

    table.insert(dict(key='val1,val2'))

which is allowed, but I can't query with wild cards. Or can I?

Is there any current way to do what I want? Is there is any possibility of supporting it in the future?

**Comment by goldmonkey163com** [comment]
I'm also looking forward to using wildcards directly, but I think there is no convenient way now.
I find quick-start tutorial provides a solution:
`table = db['user'].table
statement = table.select(table.c.name.like('%John%'))
result = db.query(statement)`
Maybe it can be used with find method,but I don't take a test.

**Comment by pudo** [comment]
@Jwink3101 this isn't currently supported, since the support for complex datatypes is so different between different databases. Postgres has really good JSON and ARRAY types, but I think MySQL is way behind on this. The ugly solution is to manually make a JSON string, but that just seems overly hacky. So doesn't seem super easy to add right now. 

@goldmonkey163com fwiw, you can also do:
```
user = db['user']
result = user.find(user.table.c.name.like('%John%'))
```

**Comment by thelittlebug** [comment]
i am monkey patching dataset to include some features.

```python
import dataset
from sqlalchemy.sql import and_

def _args_to_clause(self, args, clauses=()):
    clauses = list(clauses)
    for column, value in args.items():
        if not self.has_column(column):
            clauses.append(false())
        elif isinstance(value, (list, tuple)):
            clauses.append(self.table.c[column].in_(value))
        elif isinstance(value, dict):
            key = list(value.keys())[0]
            if key == 'like':
                clauses.append(self.table.c[column].like(value[key]))
            else:
                clauses.append(false)
        else:
            clauses.append(self.table.c[column] == value)
    return and_(*clauses)

dataset.table.Table._args_to_clause = _args_to_clause
```

usage
```python
db['customer'].find(email={'like': email})
```

**Comment by pudo** [comment]
@thelittlebug wow, I really like the DSL here, especially the transparent in_ handling. Wanna make a PR?
