### ISSUE TITLE
Expose and document Database.engine

### ISSUE THREAD

**Issue by dcbb** [pudo/dataset#215]
Sometimes it is useful to access the underlying sqlalchemy engine. For this, it would be nice if it was documented (I found it reading the source), or even supported with a getter and probably an example in the docs.

Why? For working with libraries that can do something with a DB connection, like Pandas. Specifically, in my project,

    dataframe = pandas.read_sql(sql, con=db.engine)

is an order of magnitude faster than creating lists or dictionaries from the result set and passing those to Pandas. The combination of dataset and Pandas is really nice, so I think this would benefit others.

And btw: I LOVE dataset!

**Comment by pudo** [comment]
I would actually discourage the direct use of ``db.engine``, which is not subject to transactional contexts etc. Instead, use ``db.executable`` (which is a SQLAlchemy ``Connection`` instance) where ever possible. ``db.executable`` is exposed and documented.
