### ISSUE TITLE
Split datafreeze into it's own module

### ISSUE THREAD

**Issue by pudo** [pudo/dataset#217]
The vast majority of ``dataset`` users seem to only be using the persistence part of the application, not the flat-file dumping component. Since the latter is largely independent of the former, they should live in separate packages.

Making this transition will require a major version semver release.

**Comment by eyeseast** [comment]
FWIW, I'm nearly always using both together (`dataset` to load, `datafreeze` for analysis). But I don't see any problem having them separate.

**Comment by gka** [comment]
I agree. But then we need a second spirit animal... Any suggestions?

**Comment by eyeseast** [comment]
A frozen mole rat?

**Comment by pudo** [comment]
This is now live: https://github.com/pudo/datafreeze and on PyPI
