### ISSUE TITLE
Asyncio

### ISSUE THREAD

**Issue by lormayna** [pudo/dataset#219]
Is dataset supporting asyncio?

**Comment by pudo** [comment]
I think it would be pretty cool, but dataset is dependent on upstream SQLAlchemy, whose author is making an equally valid argument for why he doesn't want to support it: http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/ -- so unless we do it at the fairly high level of abstraction that dataset provides, it doesn't look very good.
