### ISSUE TITLE
Cannot set type argument in Table.create_column()

### ISSUE THREAD

**Issue by aernesto** [pudo/dataset#222]
Hi,
If this is not the place where I should post this question, please let me know and I will be happy to post it elsewhere.

---
I tried to reproduce your example from the [documentation](https://dataset.readthedocs.io/en/latest/api.html#database):
```
table3 = db.create_table('population3',
                         primary_id='city',
                         primary_type=db.types.text)
```
but Python 3 returns the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-5e2e59dae3cc> in <module>()
      1 table3 = db.create_table('population3',
      2                          primary_id='city',
----> 3                          primary_type=db.types.text)

AttributeError: 'Database' object has no attribute 'types'
```
I am performing all of this on a [Jupyter notebook](http://jupyter-notebook.readthedocs.io/en/latest/).

I tried to investigate in a very basic manner, with the following commands/outputs:
`type(db)` returns
```
dataset.persistence.database.Database
```
`db.__dict__.keys()` returns
```
dict_keys(['lock', 'local', 'schema', 'engine', 'url', 'row_type', 'ensure_schema', '_tables', 'metadata'])
```

Any help would be appreciated

**Comment by pudo** [comment]
Hey, it looks to me like you're looking at the documentation for ``latest`` but using dataset 0.8.x or prior. The ``db.types`` thing will become available after you run a ``pip install --upgrade dataset``.

**Comment by aernesto** [comment]
Thank you! It solved it.
