### ISSUE TITLE
Jedi doesn't autocomplete functions and methods properly

### ISSUE THREAD

**Issue by esauvisky** [pudo/dataset#223]
_I'm a new user to Python, so I don't know exactly what I'm doing. Sorry if this is not the right place to ask this._ 

I'm using Anaconda with Sublime Text 3 as my Python IDE.
As I understand, Anaconda uses jedi to find autocompletions for imported packages.

However, when trying the sample script of dataset:
        
    db = dataset.connect('sqlite:///ebay.db')
    table = db['searches']
    table.insert [...]
         ^ problem happens there`

After the dot, I get no autocompletion of _insert_ (or any other functions).
When I try it in the python console it works fine. 

I tried to debug it and narrowed down the problem to either _jedi_ or _dataset_.
_At Python console:_

    >>> from jedi import Script
    >>> print(Script('import dataset;dataset.table.').completions())

_Returns:_

    [<Completion: and_>, <Completion: ClauseElement>, <Completion: Column>, <Completion: DatasetException>, <Completion: ensure_tuple>, <Completion: expression>, <Completion: false>, <Completion: func>, <Completion: Index>, <Completion: index_name>, <Completion: log>, <Completion: logging>, <Completion: normalize_column_name>, <Completion: normalize_table_name>, <Completion: NoSuchTableError>, <Completion: QUERY_STEP>, <Completion: ResultIter>, <Completion: select>, <Completion: SQLATable>, <Completion: Table>, <Completion: threading>, <Completion: Types>, <Completion: warnings>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>]

Note there is no `Completion: insert` there.

If I try listing the completions of *dataset.* it works though:

    >>> from jedi import Script
    >>> print(Script('import dataset;dataset.').completions())

Returns:

    [<Completion: connect>, <Completion: Database>, <Completion: database>, <Completion: os>, <Completion: row_type>, <Completion: Table>, <Completion: table>, <Completion: types>, <Completion: util>, <Completion: warnings>, <Completion: __all__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>]

As you can see, `Completion: connect` is there, for example.

Am I missing anything? Am I doing something stupidly wrong? Sorry if this is completely trivial.

**Comment by stefanw** [comment]
You're confusing two different things: 

- `import dataset; dataset.table` gives you the module `table` (as in `dataset/table.py`)
- `db['searches']` gives you an instance of the class `dataset.table.Table`

I would suspect the reason that autocompletion fails is that Jedi's static analysis can't discern what type will be returned by the `__getitem__` call of `db['searches']`.

I would not see failure to autocomplete in a Python library as a bug, but this might be an incentive to add type hinting or at least provide the type in doc strings where they are missing (we are still supporting Python 2.7). Feel free to open a PR.
