### ISSUE TITLE
Strange issue with create_table and SQLite when database file doesn't exist initially

### ISSUE THREAD

**Issue by cheese528** [pudo/dataset#228]
Hi,
I was trying out this library and hit a strange issue, possibly due to not understanding something.

When I tried to call connect() followed create_table() when pointed to a sqlite3 file that doesn't initially exist, the file gets created, but the table doesn't get created until I do something like print table.  See the sample code here:

```python
    import dataset

    class Test(object):
        def __init__(self):
            self.url = None
            self.tablename = None
            self.db = None
            self.table = None

        def connect(self):
            self.db = dataset.connect(self.url)
            self.table = self.db.create_table(self.table)

    if __name__ == '__main__':
        testdb = Test()
        testdb.url = 'sqlite:///test.db'
        testdb.tablename = 'test'
        testdb.connect()
        print 'tables are', testdb.db.tables # empty set
        print 'table column is', testdb.table.columns # no columns yet
        print testdb.table
        print 'tables are now', testdb.db.tables # table is now there
        print 'table column is', testdb.table.columns # automatic id column is there too
```

The resulting output:
```
    tables are []
    table column is []
    <Table(test)>
    tables are now [u'test']
    table column is ['id']
```
The db file gets created at the point of the 'connect() call, but somehow the table doesn't unless I do the print.  Does anyone have an idea what I need to do to force the initialization of the initial table besides using the print?

Edit: I'm using Python 2.7.11 on 64-bit Windows 10.  Also a mistype in the sample code.

**Comment by pudo** [comment]
This is intentional, I'm sorry that it is surprising: the table is only really created when the first write operation is performed on the dataset object. There's some odd technical for why this makes sense (specifically: tables with no primary key, dropping and re-creating tables inline). Does this unexpected behaviour actually cause an issue for you?
