### ISSUE TITLE
Table.exists fails for view

### ISSUE THREAD

**Issue by iszerotoo** [pudo/dataset#235]
when i using version 0.8 , i could load a view like this:
db=dataset.connect('sqlite:///some.db')
view = db['view_name']
view.exists # this get true

but when i recently upgrade to 1.05, this did not work
view.exists # this get false, not always but very often

why? is this version designed to work like this or its a bug ?

**Comment by benjaminweb** [comment]
Same behaviour here on 1.0.6. It seems that views are not reflected by default while the opposite is expected.

Can we draft a test baseline for in https://github.com/pudo/dataset/blob/master/test/test_dataset.py?
Something like the following:

```python
from sqlalchemy import Table
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.expression import Executable, ClauseElement

class CreateView(Executable, ClauseElement):
    def __init__(self, name, select):
        self.name = name
        self.select = select

@compiles(CreateView)
def visit_create_view(element, compiler, **kw):
    return "CREATE VIEW %s AS %s" % (
         element.name,
         compiler.process(element.select, literal_binds=True)
         )

# test data
from sqlalchemy import MetaData, Column, Integer
from sqlalchemy.engine import create_engine
engine = create_engine('sqlite://')
metadata = MetaData(engine)
t = Table('t',
          metadata,
          Column('id', Integer, primary_key=True),
          Column('number', Integer))
t.create()
engine.execute(t.insert().values(id=1, number=3))
engine.execute(t.insert().values(id=9, number=-3))

# create view
createview = CreateView('viewname', t.select().where(t.c.id>5))
engine.execute(createview)

# reflect view and print result
v = Table('viewname', metadata, autoload=True)
for r in engine.execute(v.select()):
    print(r)
```
Source: https://stackoverflow.com/questions/9766940/how-to-create-an-sql-view-with-sqlalchemy#9769411

I wonder that `reflect_views` of class `database.Database` does not gets used at all at initialisation time: https://github.com/pudo/dataset/blob/master/dataset/database.py#L29

=> What would be needed to done to get this working?

**Comment by mrmango** [comment]
Would this explain why I can't select data from views?

**Comment by beh333** [comment]
I observe Table.exists returns false for views, until I force the execution of _reflect_table(). I am setting reflect_views=True. I see this with mysql and sqlite. I am using dataset 1.1.2.

Can we maybe edit the title of this issue so that it's more specific without the red herring of sqlite. I suggest "Table.exists fails for views"

**Comment by luerhard** [comment]
Wow, thank you very much for fixing this in 1.2.0!
Is there any schedule, when the version will be released on pypi?

**Comment by pudo** [comment]
Ups, I forgot to run the release scripts :) Out now - get it while it's hot.
