### ISSUE TITLE
SQLite, Pool and threading warning

### ISSUE THREAD

**Issue by saimn** [pudo/dataset#238]
Since ffea0f7a69d88d97b4e974e4475805e37ab38587, a "multi-threading warning" is displayed when dataset changes the schema inside a transaction, and I'm looking for the best way to avoid this warning. 
With #163 the `StaticPool` is used by default for SQLite, which should be safe regarding multi-threading ?
And even if I use the `NullPool`, I still get the warning, and don't understand why. Do you have any hint here ?

**Comment by pudo** [comment]
This isn't so much a technical issue as a conceptual one which I just don't know the answer to. It has nothing to do with connection pooling.

Imagine you're running a multi-threaded script where two threads are both trying to modify the schema for a table inside of a transaction: one is trying to add a column ``bla`` with type ``integer``, the other is trying to add a column with the same name (and possibly a different type, say, ``text``). Essentially they're creating a conflict in the schema.

Around dataset 0.4 this was unhandled and lead to crashes. Around 0.6 we made it so schema changes would run outside the active transaction, which lead to deadlocks. So now I've just put in the warning.

The idea way to avoid this is to insert the first row of data before multi-threading, but obviously that's not always possible. Still searching for an ideal solution here...

**Comment by frogger72** [comment]
I'm having the exact same issue here.. receiving these warnings when not using multi-threading

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.

**Comment by pudo** [comment]
@saimn the pool really doesn't create threads, unless its behaviour is radically dependent on some factors not present on any of my servers. Beyond that, I don't know how to help you: remove the warning to make the error implicit again?
