### ISSUE TITLE
how to clearing or shutting down the connections

### ISSUE THREAD

**Issue by l976308589** [pudo/dataset#246]
There is no way of explicitly clearing or shutting down the connections, other than having the dataset instance garbage collected.

def test():
     with dataset.connect(self.sql_url) as db:
          db[self.orders_table].update({'Label': label, 'Account': account, 'State': 1}, ['Label', 'Account'])

when I run this function(postgresql),dataset will build a new connection.After a while, warning too many clients already.

how to clearing or shutting down the connections.

Thanks.

**Comment by mrmango** [comment]
Hi,

You have already seen the quote on the API most likely? There is no other way then to garbage collect.

"dataset uses SQLAlchemy connection pooling when connecting to the database. There is no way of explicitly clearing or shutting down the connections, other than having the dataset instance garbage collected."
