### ISSUE TITLE
UPSERT MANY

### ISSUE THREAD

**Issue by ohld** [pudo/dataset#249]
I just found your library and it's amazing!
But I can't find method for UPSERT MANY sql-query.

For example, in `sqlite3`library I often use this calls:

```python
db.executemany('REPLACE INTO .... ', list_of_dicts)
```

Can you please implement this method or give me the way how can I make it with already existing ones? Thanks!

**Comment by pudo** [comment]
I'm keen to have support for it, especially if it supports multiple backends (postgres, sqlite, ...). Wanna make a PR?

**Comment by saimn** [comment]
I have a upsert_many helper function which just calls `Table.upsert` in a loop within a transaction block. Happy to make a PR with this, but maybe there is better way with sqlalchemy ?
