### ISSUE TITLE
Unique and Not Null

### ISSUE THREAD

**Issue by patarapolw** [pudo/dataset#266]
I would like to see these two, at least, in a schema-less NoSQL. How do I specify it is `dataset`?

I managed to [create such in TinyDB](https://github.com/patarapolw/tinydb-constraint), but the main problems of TinyDB are:
- Slow `insert_one`
- No support of BLOB/binary

BTW, does `dataset` support blob?

Another interesting thing is ForeignKey, but I believe it will never be supported, anyway.

**Comment by patarapolw** [comment]
I have found an answer, by using SQLAlchemy, **minimally**.

	import dataset
	import sqlalchemy as sa
	
    db = dataset.connect('sqlite:///' + db_file)

    if not os.path.exists(db_file):
        sa.Table(
            'patient', self.db.metadata,
            sa.Column('patient_id', sa.Integer, primary_key=True)
        ).create()
        sa.Table(
            'patho_report', self.db.meta,
            sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
            sa.Column('patho_id', sa.String, nullable=False, unique=True),
            sa.Column('patient_id', sa.Integer, sa.ForeignKey('patient.patient_id')),
            sa.Column('received', sa.DateTime)
        ).create()

**Comment by pudo** [comment]
You can now do:

```python
import dataset

db = dataset.connect('sqlite:///' + db_file)
report = db['patho_report']
report.create_column('patho_id', nullable=False, unique=True)
```

Foreign keys are, I think, going to remain out of scope unless anyone comes up with a super Pythonic way to express them.
