### ISSUE TITLE
uppercase column names 

### ISSUE THREAD

**Issue by codefatherru** [pudo/dataset#270]
I suppose this is a bug (I couldn't google it)
if you have got database table with column 'Tags' (capitalize  first letter)
try
```
table.insert(dict(name='Jane Doe', age=37, country='France', gender='female', tags = 'tag'))
#  lowercase letters only 
```
you will  get

> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: tags [SQL: 'ALTER TABLE csv ADD COLUMN tags TEXT'] (Background on this error at: http://sqlalche.me/e/e3q8)

it comes as if table.insert is caseSensitive when checks for columns, but caseINsensitive when tries to create them

P.S.
I hope this issue will save several hours for someone

**Comment by kwinata** [comment]
Based on [this discussion](https://stackoverflow.com/a/50928439/8809992), SQLite seems to have case-insensitive column names. Shall we convert/enforce every column name to be lowercase? We can do that in [here](https://github.com/pudo/dataset/blob/43e9431865365d3c22a46ec15940ea22c0543b26/dataset/util.py#L73). However, this will introduce backward incompatibility. I think a better approach is just to raise a more descriptive error before it goes inside the SQL Alchemy.

**Comment by pudo** [comment]
This should now throw a hard error now, making this ambiguity easier to debug. We can't really gloss over it in DBMS that make a distinction.
