### ISSUE TITLE
Add method to create multiple columns

### ISSUE THREAD

**Issue by saimn** [pudo/dataset#273]
I need to create a set of columns to be sure that they exist with the correct type (this is minor annoyance with the automatic creation, if a value for a column is None it will not be created with the expected type).

So it is currently possible to do a loop with `Table.create_column`, but it would be more efficient to have a way to create directly a set of columns (or just ensure that they exists with the correct type). I guess that making `Table._sync_columns` a public method would be enough. Thoughts?

**Comment by Red-Eyed** [comment]
Why just not to use following construction like in the docs?
`# dataset will create "missing" columns any time you insert a dict with an unknown key
table.insert(dict(name='Jane Doe', age=37, country='France', gender='female'))`

**Comment by saimn** [comment]
That's what `_sync_columns` does, and other methods like `insert` are relying on it to create the columns, so making it public would be great.
https://github.com/pudo/dataset/blob/22b64ee4806017e8ba59a94def7f19c8fd3573f2/dataset/table.py#L258-L264
