### ISSUE TITLE
Unable to Pip Install Dataset

### ISSUE THREAD

**Issue by liquidgenius** [pudo/dataset#274]
After a clean install of OSX Mojave 10.14.2 I can no longer PIP install Dataset into a Anaconda Python3.6.5 environment. The error below lists GCC as a problem during the build. I attempted to install GCC again using Homebrew to no avail. I then wiped and reinstalled Mojave with the same results.

I also attempted to PIP install Dataset into the root system environment with the same results.

I can install other python modules into both the root system and Anaconda environments.

Any direction on getting Dataset working again would be greatly appreciated. Errors below:

> Collecting dataset
>   Using cached https://files.pythonhosted.org/packages/ba/76/5b8fe80f487bfa90b8d0094c3a27150fe797b1fbe02dec31b048fd52448d/dataset-1.1.0-py2.py3-none-any.whl
> Collecting sqlalchemy>=1.1.0 (from dataset)
> Requirement already satisfied: six>=1.11.0 in /Users/jz/anaconda3/envs/bridge/lib/python3.6/site-packages (from dataset) (1.12.0)
> Collecting normality>=0.5.1 (from dataset)
>   Using cached https://files.pythonhosted.org/packages/7f/38/9ed937afe0fe95a281180d8820d46eb955bc1b0f656f3b301635608a5c1f/normality-1.0.0-py2.py3-none-any.whl
> Collecting alembic>=0.6.2 (from dataset)
> Collecting banal>=0.4.1 (from normality>=0.5.1->dataset)
>   Using cached https://files.pythonhosted.org/packages/27/07/376d107ccf0dd80efdd8e4310b1d7d34a2d54f5389f946d58950c6dd70cc/banal-0.4.2-py2.py3-none-any.whl
> Collecting chardet (from normality>=0.5.1->dataset)
>   Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
> Collecting pyicu>=1.9.3 (from normality>=0.5.1->dataset)
>   Using cached https://files.pythonhosted.org/packages/c2/15/0af20b540c828943b6ffea5677c86e908dcac108813b522adebb75c827c1/PyICU-2.2.tar.gz
> Collecting Mako (from alembic>=0.6.2->dataset)
> Requirement already satisfied: python-dateutil in /Users/jz/anaconda3/envs/bridge/lib/python3.6/site-packages (from alembic>=0.6.2->dataset) (2.7.5)
> Collecting python-editor>=0.3 (from alembic>=0.6.2->dataset)
> Collecting MarkupSafe>=0.9.2 (from Mako->alembic>=0.6.2->dataset)
>   Using cached https://files.pythonhosted.org/packages/da/fc/2979c425ad23d528d6ac2e1f3efdc28e572fa1e1fbd5a75171cbdd7ddaa5/MarkupSafe-1.1.0-cp36-cp36m-macosx_10_6_intel.whl
> Building wheels for collected packages: pyicu
>   Running setup.py bdist_wheel for pyicu: started
>   Running setup.py bdist_wheel for pyicu: finished with status 'error'
>   Complete output from command /Users/jz/anaconda3/envs/bridge/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8v/wnw63nls49572vj7073gzn4w0000gn/T/pycharm-packaging/pyicu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/8v/wnw63nls49572vj7073gzn4w0000gn/T/pip-wheel-q_nht7jo --python-tag cp36:
>   
>   Building PyICU 2.2 for ICU 58.2
>   
>   Adding CXXFLAGS="-I/Users/jz/anaconda3/include" from /Users/jz/anaconda3/bin/icu-config
>   Adding LDFLAGS="-Wl,-rpath,/Users/jz/anaconda3/lib -L/Users/jz/anaconda3/lib -licui18n -licuuc -licudata" from /Users/jz/anaconda3/bin/icu-config
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.macosx-10.7-x86_64-3.6
>   copying PyICU.py -> build/lib.macosx-10.7-x86_64-3.6
>   creating build/lib.macosx-10.7-x86_64-3.6/icu
>   copying icu/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/icu
>   warning: build_py: byte-compiling is disabled, skipping.
>   
>   running build_ext
>   building '_icu' extension
>   creating build/temp.macosx-10.7-x86_64-3.6
>   gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jz/anaconda3/envs/bridge/include -arch x86_64 -I/Users/jz/anaconda3/envs/bridge/include -arch x86_64 -I/Users/jz/anaconda3/envs/bridge/include/python3.6m -c _icu.cpp -o build/temp.macosx-10.7-x86_64-3.6/_icu.o -DPYICU_VER="2.2" -I/Users/jz/anaconda3/include
>   warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
>   In file included from _icu.cpp:27:
>   ./common.h:38:13: error: unknown type name 'decltype'
>       typedef decltype(nullptr) nullptr_t;
>               ^
>   ./common.h:38:30: error: expected ';' after top level declarator
>       typedef decltype(nullptr) nullptr_t;
>                                ^
>                                ;
>   In file included from _icu.cpp:27:
>   In file included from ./common.h:106:
>   In file included from /Users/jz/anaconda3/include/unicode/unistr.h:33:
>   /Users/jz/anaconda3/include/unicode/std_string.h:35:10: fatal error: 'string' file not found
>   #include <string>
>            ^~~~~~~~
>   1 warning and 3 errors generated.
>   error: command 'gcc' failed with exit status 1
>   
>   ----------------------------------------
>   Running setup.py clean for pyicu
> Failed to build pyicu
> Installing collected packages: sqlalchemy, banal, chardet, pyicu, normality, MarkupSafe, Mako, python-editor, alembic, dataset
>   Running setup.py install for pyicu: started
>     Running setup.py install for pyicu: finished with status 'error'
>     Complete output from command /Users/jz/anaconda3/envs/bridge/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8v/wnw63nls49572vj7073gzn4w0000gn/T/pycharm-packaging/pyicu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/8v/wnw63nls49572vj7073gzn4w0000gn/T/pip-record-yz3yw6d5/install-record.txt --single-version-externally-managed --compile:
>     
>     Building PyICU 2.2 for ICU 58.2
>     
>     Adding CXXFLAGS="-I/Users/jz/anaconda3/include" from /Users/jz/anaconda3/bin/icu-config
>     Adding LDFLAGS="-Wl,-rpath,/Users/jz/anaconda3/lib -L/Users/jz/anaconda3/lib -licui18n -licuuc -licudata" from /Users/jz/anaconda3/bin/icu-config
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.macosx-10.7-x86_64-3.6
>     copying PyICU.py -> build/lib.macosx-10.7-x86_64-3.6
>     creating build/lib.macosx-10.7-x86_64-3.6/icu
>     copying icu/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/icu
>     warning: build_py: byte-compiling is disabled, skipping.
>     
>     running build_ext
>     building '_icu' extension
>     creating build/temp.macosx-10.7-x86_64-3.6
>     gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jz/anaconda3/envs/bridge/include -arch x86_64 -I/Users/jz/anaconda3/envs/bridge/include -arch x86_64 -I/Users/jz/anaconda3/envs/bridge/include/python3.6m -c _icu.cpp -o build/temp.macosx-10.7-x86_64-3.6/_icu.o -DPYICU_VER="2.2" -I/Users/jz/anaconda3/include
>     warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
>     In file included from _icu.cpp:27:
>     ./common.h:38:13: error: unknown type name 'decltype'
>         typedef decltype(nullptr) nullptr_t;
>                 ^
>     ./common.h:38:30: error: expected ';' after top level declarator
>         typedef decltype(nullptr) nullptr_t;
>                                  ^
>                                  ;
>     In file included from _icu.cpp:27:
>     In file included from ./common.h:106:
>     In file included from /Users/jz/anaconda3/include/unicode/unistr.h:33:
>     /Users/jz/anaconda3/include/unicode/std_string.h:35:10: fatal error: 'string' file not found
>     #include <string>
>              ^~~~~~~~
>     1 warning and 3 errors generated.
>     error: command 'gcc' failed with exit status 1
>     
>     ----------------------------------------
> 
>   Failed building wheel for pyicu
> Command "/Users/jz/anaconda3/envs/bridge/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8v/wnw63nls49572vj7073gzn4w0000gn/T/pycharm-packaging/pyicu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/8v/wnw63nls49572vj7073gzn4w0000gn/T/pip-record-yz3yw6d5/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8v/wnw63nls49572vj7073gzn4w0000gn/T/pycharm-packaging/pyicu/
>

**Comment by miek770** [comment]
Hi @liquidgenius,

I'm simply passing by but your issue isn't with dataset's installation but with pyicu's, see your own log. I suggest you try googling the error messages it throws and contact pyicu's team if you fail to find a solution.

**Comment by liquidgenius** [comment]
@miek770 thank you for the direction. I'll close this issue.

**Comment by liquidgenius** [comment]
The following Terminal command may need to be issued for pyicu to properly install on OSX. Ensure that the DPYICU_VER matches the pyicu module version being installed. It should be issued prior to the pip or pipenv install command is issued for package pyicu==2.2. Pyicu should be installed prior to installing Dataset.

export PYICU_CFLAGS=-std=c++11:-DPYICU_VER='"2.2"'

**Comment by remorses** [comment]
i face this iussue installing in python:3.6-alpine so i think this is still relevant. I think the package should remove the pyicu dependency totally given his unstability. What is the dependency using pyicu?

**Comment by remorses** [comment]
OK i found that pyicu is required by normality package, one solution would be to substitute the functions used by normaility with others from another package or instead remove the pyicu dependency from normality, given that both packages are owned by @pudo, better to ask him first. What is the best option? pool request on `dataset` or `normality`?

**Comment by remorses** [comment]
Turns out normality package was unused, opened #280 to remove the dependency.

**Comment by liquidgenius** [comment]
Closing, please reference #280.
