### ISSUE TITLE
Create user-defined function

### ISSUE THREAD

**Issue by luboss** [pudo/dataset#286]
I'm looking for a feature to create user defined function that will be able to use in SQL queries. Sqlite3 module does allow this:
`sqlite3.Connection.create_function(name, num_params, func)`

Is it possible to leverage this feature? SQLAlchemy is also capable of this using the register() method.
I'm using _sqlite:///:memory:_ as database engine. I could load the created database with sqlite module but I'm sure there must be better way to do it.

**Comment by pudo** [comment]
I don't think this should be within scope of `dataset`. You can always access the original SQLAlchemy engine and its functionality at `db.engine` and push in a function there.

**Comment by luboss** [comment]
Ok, this is very interesting because after db = dataset.connect(...) I was inspecting db instance to see any relation to sqlalchemy by help(db) but I could not find any. API is not mentioning this either. After your reply I tried randomly access db.engine and surprisingly I can see it is available.
How can I explore the attributes and methods of the db object instance without API and help()?
