### ISSUE TITLE
In autogeneration of tables datatype always text for varchar columns

### ISSUE THREAD

**Issue by aartijain** [pudo/dataset#288]
I am trying to create a table using dataset from a CSV file. Why dataset generates all columns text instead of varchar. CSV content is as follow:

applicationCode,orderId,orderStatus,brandCode,orderType,channelTypeCode,channelSourceCode,emailAddress,orderCreatedDateTime,orderUpdatedDateTime,referralCode,salesAgentId,salesAgentName,totals_orderShippingTaxed,totals_orderShippingTaxAmount,totals_orderSubtotalTaxed,totals_orderSubtotalTaxAmount,totals_totalOrderDiscount,totals_grandTotalTaxed,totals_grandTotalTaxAmount,totals_orderCurrencyCode,etl_ref
ABC00,4000080771,NEW,TE,ZO01,TEST,TEST,abc@example.com,2019-02-22T09:01:01Z,,,,,9,,64,,,64,,GBP,d7506e0c-f708-451f-aec3-204ce155f901

**Comment by pudo** [comment]
If `dataset` were to make that distinction, how would it know? Would it judge this purely from the length of the first text value? It feels to me like wanting that type of precision might be indicative that your use case has exceeded the scope of dataset and you might want to adopt an ORM.

It's also worth mentioning that on some database systems it doesn't make that much of a difference. In Postgres, for example, my understanding is that everything is handled as text internally.
