### ISSUE TITLE
how to create_index within definition of table?

### ISSUE THREAD

**Issue by beh333** [pudo/dataset#293]
Hi and thanks for dataset. I want to create indexes. I'd like to use table.create_index(), but this only takes effect after I create the table and insert data. The [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/create-index.html) recommends creating indexes when the table is defined, before any data goes in. Is there a way with dataset to define an empty table with indexes, as recommended by MySQL? Thanks!

**Comment by pudo** [comment]
I think you could just run `table.create_index` directly after `db.create_table`. This will not create the index if it already exists; so it's safe to run each time. It seems preferable to me to have this be two separate calls unless we can come up with a really neat syntax to feed into `db.create_table`.
