### ISSUE TITLE
Can't execute 'from stuf import stuf'

### ISSUE THREAD

**Issue by therden** [pudo/dataset#303]
Recently found dataset, and am interested in using in a project.  But I found a problem while following along in the examples in *Quickstart*.  Attempting to execute 

```from stuf import stuf```

as shown at the end of the "Reading Data from Tables: section results in

```No module found named 'stuf'```

Any ideas?

**Comment by pudo** [comment]
`stuf` is a non-standard re-implementation of Python's dict type, available here: https://pypi.org/project/stuf/ 

The example is supposed to illustrate that you can inject your own dict types instead of the default, `OrderedDict`...
