### ISSUE TITLE
MySQLdb._exceptions.OperationalError: (1170, "BLOB/TEXT column 'email' used in key specification without a key length")

### ISSUE THREAD

**Issue by Ammadkhalid** [pudo/dataset#304]
Hi,

got this error
```
MySQLdb._exceptions.OperationalError: (1170, "BLOB/TEXT column 'email' used in key specification without a key length")
```
code
```
query = dict(email=email, password=password, total_storage=total_storage,
                     used_storage=used_storage, free_storage=free_storage,
                     is_full=is_full)
        return self.pool.upsert(query, ['email'])
```
pool is the table

is this happening because of mysql version? sorry i don't have strong knowledge of databaset stuff rn :)
thanks a lot.

**Comment by pudo** [comment]
I haven't seen this, either. Is it possible you inserted the password as a binary object, not a string?

**Comment by pudo** [comment]
I'm closing this because of lack of feedback, reasonably sure that what happened is that the password hash digest function return the hashed password as a `bytes` object, which then couldn't be usefull inserted into the database.
