### ISSUE TITLE
timestamp **with** time zone

### ISSUE THREAD

**Issue by gduverger** [pudo/dataset#326]
When I insert an aware datetime, Dataset creates a `timestamp **without** time zone` field for it.

```
>>> import dataset
>>> import datetime
>>> db = dataset.connect('postgresql://…/test')
>>> now = datetime.datetime.now(datetime.timezone.utc)
>>> db['test'].insert(dict(date=now))
```

<img width="537" alt="Screen Shot 2020-04-13 at 8 45 06 PM" src="https://user-images.githubusercontent.com/93743/79174116-b06b3000-7dc7-11ea-9382-294f2681d224.png">

Is there a way to make that field `timestamp **with** time zone`, instead? Otherwise, what's the recommended way to handle timezones with Dataset?

**Comment by therealstein** [comment]
Yes i have a similar problem. I need to set microseconds. In sqlalchemy it would be fsp=6 or something

**Comment by pudo** [comment]
You can create columns explicitly if you wish to set a very specific type: 

```python
from sqlalchemy.types import DateTime

table = db['my_new_table']
table.create_column('date', DateTime(timezone=True))
```

See also the SQLA type documentation: https://docs.sqlalchemy.org/en/13/core/type_basics.html
