### ISSUE TITLE
Postgres search_path

### ISSUE THREAD

**Issue by kushtun** [pudo/dataset#327]
Question -- using `dataset` seems to require the connect be URL-ish.  Given that a lot of Pg dbs are set up not under `public`, usually need to specify a schema in the connect info.  How do we do that with `dataset`?  Seems like the API examples are based around querying, can one issue a general SQL statement somehow to set the schema that way as well, or is there some syntax that allows it to go in the URL?

Not seeing a way to get to non-public schemas in `dataset` Pg connections.

**Comment by pudo** [comment]
You can pass a `schema` argument into `dataset.connect` to specify the PG search path.
