### ISSUE TITLE
get_table ignores ensure_schema flag

### ISSUE THREAD

**Issue by astenuz** [pudo/dataset#330]
Hi! As I understand, when connecting to a database we could set `ensure_schema=False` to avoid table and column creation. However, it seems this flag is ignored when accessing tables. For example, I believe it makes sense that when the flag is set to `False`, loading a non-existing table should raise an exception. However, it creates the table with a single `id` column:

```python
import dataset

db = dataset.connect('<connection>', ensure_schema=False)

db['non_existing_table']  # creates the table, ignoring ensure_schema
```

This happens because `get_table(...)` (the method [] uses under the hood) directly calls `create_table(...)` [without checking the flag](https://github.com/pudo/dataset/blob/0c46d9eead35ab89e6c7ae52ce7c9d51216c77ca/dataset/database.py#L221)

**Comment by pudo** [comment]
You're right, that behaviour is inconsistent. Fixing.
