### ISSUE TITLE
JSON Partial updates in MySQL with update / upsert

### ISSUE THREAD

**Issue by d3vr** [pudo/dataset#333]
Hello, 

Is there any way to achieve a [JSON partial update](https://dev.mysql.com/doc/refman/8.0/en/json.html) (using JSON_SET()) in MySQL when using the update / upsert methods ? 

Thanks

**Comment by pudo** [comment]
I don't think there is from the `dataset` API. Maybe the underlying `sqlalchemy` library can be used to do this - I'd check their excellent docs!

**Comment by d3vr** [comment]
Thanks for your reply, so I guess it's out of the scope of dataset, will have a look on sqlalchemy's docs.
