### ISSUE TITLE
`.distinct` should return distinct values

### ISSUE THREAD

**Issue by jfilter** [pudo/dataset#337]
Hello @pudo, great work, all cool, but: I stumbled upon the usage of `.distinct`. I expected dataset to return values and not rows. I don't really see a usage for the 'raw' output of `db.query`. So my proposal: return an iterator over the values.

```python
subs = tab_incidents.distinct('subdivisions')
list(map(lambda x: x['subdivisions'], subs))
```

**Comment by pudo** [comment]
How would this handle `.distinct('divisions', 'subdivisions')`?

**Comment by jfilter** [comment]
Option 1

Only return the raw values for single columns. So don't change anything for multiple columns.

Option 2

Return tuples

**Comment by pudo** [comment]
I feel it's icky to break the API in this way. If you want to submit a PR to add a second function, e.g. `distinct_items` or so, it's very welcome!
