### ISSUE TITLE
Able to create tables even when ensure_schema is True

### ISSUE THREAD

**Issue by achillesrasquinha** [pudo/dataset#342]
If you attempt to execute the following:

```python
import dataset

db = dataset.connect(ensure_schema=True)
db['Foo'].insert({ 'foo': 'bar' })
```

ends up creating `Foo` and inserting the data. Is this the required behaviour?

**Comment by pudo** [comment]
Yes. `ensure_schema` in dataset means "make sure the schema is as needed to store the given data, create it if needed". Try the opposite setting to disable automatic schema creation.

**Comment by achillesrasquinha** [comment]
Works! Closing this.
