### ISSUE TITLE
[QUESTION] How do I make a simple find query ignoring character case?

### ISSUE THREAD

**Issue by DataGreed** [pudo/dataset#349]
I want to find a record in the database by a string ignoring it's character case, how do I do that?

**Comment by pudo** [comment]
You can do: 

```python
tbl = ds['my_table']
rows = tbl.find(('field', 'ilike', 'text'))
```

This might not be the fastest thing in the world, but it'll do the trick.

**Comment by DataGreed** [comment]
@pudo thank you so much!
