### ISSUE TITLE
CleverDict instead of stuf

### ISSUE THREAD

**Issue by garyrob** [pudo/dataset#358]
CleverDict is much better documented than stuf, and looks like a much more active project, and seems to work pretty much the same way from the perspective of using it with dataset. 

So, just a small suggestion: modify the dataset docs to reference CleverDict instead of stuf.

https://pypi.org/project/cleverdict/

**Comment by pudo** [comment]
It's an example. ``stuf`` is not used anywhere in ``dataset``.
