### ISSUE TITLE
How do I use "AND", "OR" logical operators with .find() ?

### ISSUE THREAD

**Issue by DataGreed** [pudo/dataset#369]
How do I use "AND", "OR" logical operators with `.find()` ?

I've looked through the docs, but didn't find anything on it. The only page about operators is this one, but it does not list "AND" and "OR" operators.

**Comment by pudo** [comment]
It's not supported. The whole query operators thing has escalated a bit, it was originally meant to be "equals, or write your own query". There's not really an overarching plan for some query DSL in dataset (like MongoDB queries or something), so I'd be reluctant to add this ad-hoc.
