### ISSUE TITLE
Installable via conda

### ISSUE THREAD

**Issue by wholtz** [pudo/dataset#370]
I would like to see dataset be installable via conda.

**Comment by nlindner** [comment]
I'm not a contributor to dataset, just a happy user. But it recently became installable from the conda-forge channel. Here are the feedstocks for [dataset](https://github.com/conda-forge/dataset-feedstock) and for its required package [banal](https://github.com/conda-forge/banal-feedstock).

IIRC, then in my setup (running Miniconda on Windows, where my .condarc channels include both `conda-forge` and `defaults`), I first had to unhook dataset from pip by uninstalling it and banal with: `pip uninstall dataset banal`. Once I did that, then `conda install dataset` (re)installed dataset and banal.

**Comment by wholtz** [comment]
Thanks @nlindner, I'm not sure how I overlooked it on Conda-forge.
