### ISSUE TITLE
TIMESTAMPTZ Datatype for PostgreSQL

### ISSUE THREAD

**Issue by nagabrahmam-mantha** [pudo/dataset#378]
Hi, How can I create a column with datatype of TIMESTAMPTZ (in PostgreSQL). 

I tried using this: 
table.create_column('datetime', db.types.TIMESTAMPTZ)

But its giving error:
AttributeError: 'Types' object has no attribute 'TIMESTAMPTZ'

What is the right way?

Thanks.

**Comment by pudo** [comment]
I don't have much experience with TIMESTAMPTZ, but judging from [this SO answer](https://stackoverflow.com/questions/54796888/using-postgres-time-with-timezone-with-sqlalchemy) you should be able to do this: 

```python
from sqlalchemy import DateTime

table.create_column('datetime', DateTime(timezone=True))
```

Can you confirm?

**Comment by pudo** [comment]
assuming fixed.
