### ISSUE TITLE
count = 0

### ISSUE THREAD

**Issue by tynods** [pudo/dataset#84]
the count property on a find() or a all() is equal to 0 even if there are results...

**Comment by pudo** [comment]
I've refactored the ``ResultIter`` class to not use ``fetchone()`` any more (was needed for another ticket). 

Also, I've added a new method, ``table.count()`` which takes the same filter arguments as ``table.find()`` and will return the correct count for the result set.

**Comment by pudo** [comment]
Fixed in e662d8bde73084a4d77d6c26205fe4b5ff2e83ec
