### ISSUE TITLE
Make tables look like R

### ISSUE THREAD

**Issue by kousu** [pudo/dataset#87]
R and Pandas (and slightly less readably, numpy and matlab) have syntactic sugar for slicing tables:

```{R}
landscapes[, c("runID", "happiness", "speed", "time")]
```
which produces a smaller table containing only those four columns out of the original sixteen.

I expected Dataset to have the same:
```{py}
self.db['landscapes']['runID',  "happiness", 'speed', "time"]
```

But I get
```
TypeError: 'Table' object has no attribute '__getitem__'
```

dataset is built on SQLAlchemy is built on SQL, connections, and transactions. I understand that what I'm asking would be tricky to do nicely. Still, feature requested!

The syntactic sugar allows naming columns by string or by integer, a feature which SQLAlchemy already supports I believe.

**Comment by pudo** [comment]
I thought about this a bit and decided that the simplest thing to do is to make ``__getitem__`` call distinct - returning just the full list of values would have had far fewer use cases, in my mind.

As for the ``View`` idea, I like it but it need to think about it a bit further. I do think that the current result object (which basically just yields rows) could have better semantics, but if it becomes a full, chained query builder, we're re-building ``sqlalchemy`` once more.
