### ISSUE TITLE
connecting times out when connecting to a db with an "@" in the password. 

### ISSUE THREAD

**Issue by abelsonlive** [pudo/dataset#92]
This might be a `sqlalchemy` thing, but when I try to connect to a postgres db with the following (example) url:
```python
import dataset
db_url = "postgres://drsuess:c@inthehat@123.435.123.1:5432/lorax"
db = dataset.connect(db_url)
```
The connection attempt just freezes indefinitely.  I tried changing the password and it remedied the situation, but you might want to add a check / warning for this.

-

**Comment by pudo** [comment]
Ok, I've just tried to reproduce this and it's working for me. Maybe a versioning thing? 

```python
In [14]: db
Out[14]: <Database(postgresql://foo:s@p@localhost/spendb)>
```
